# Generated by Django 6.0.5 on 2026-06-07 09:25

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appversion_appversionseen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Application Approved'), ('reject', 'Application Rejected'), ('payment', 'Payment Applied'), ('payment_status_change', 'Payment Status Changed'), ('device_lock', 'Device Locked'), ('device_unlock', 'Device Unlocked'), ('device_enroll', 'Device Enrolled'), ('kyc_change', 'KYC Document Changed'), ('contract_create', 'Contract Created'), ('claim_application', 'Application Claimed'), ('payout_request', 'Payout Requested'), ('webhook_received', 'Webhook Received')], max_length=80),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='core_auditl_target__315580_idx'),
        ),
    ]
