# Generated by Django 6.0.5 on 2026-06-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('agreement_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('signer_name', models.CharField(blank=True, max_length=200)),
                ('signer_email', models.CharField(blank=True, max_length=200)),
                ('signer_phone', models.CharField(blank=True, max_length=30)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='merchant_agreements/signatures/')),
                ('agreed_read', models.BooleanField(default=False)),
                ('agreed_good_faith', models.BooleanField(default=False)),
                ('agreed_genuine_customers', models.BooleanField(default=False)),
                ('agreed_discretion', models.BooleanField(default=False)),
                ('agreed_commissions', models.BooleanField(default=False)),
                ('agreed_electronic_signature', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='merchant_agreements/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Agreement',
                'verbose_name_plural': 'Merchant Agreements',
                'ordering': ['-created_at'],
            },
        ),
    ]
