# Generated by Django 6.0.5 on 2026-06-12 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_agreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='merchant_certificates/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='certificate_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='certificate_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='compliance_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='compliance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='compliance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_compliance_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
