# Generated by Django 6.0.5 on 2026-08-09 09:52

import django.db.models.deletion
import django.utils.timezone
import protect.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0005_add_deposit_payment_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, max_length=20, unique=True)),
                ('imei_2', models.CharField(blank=True, db_index=True, max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('financing_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('written_off', 'Written Off')], default='active', max_length=24)),
                ('protection_status', models.CharField(choices=[('protected', 'Protected'), ('reported_lost', 'Reported Lost'), ('reported_stolen', 'Reported Stolen'), ('under_recovery', 'Under Recovery'), ('recovered', 'Recovered')], default='protected', max_length=24)),
                ('device_status', models.CharField(choices=[('financed', 'Financed'), ('active', 'Active'), ('payment_locked', 'Payment Locked'), ('theft_locked', 'Theft Locked'), ('released', 'Released'), ('transferred', 'Transferred')], default='financed', max_length=24)),
                ('resale_status', models.CharField(choices=[('not_eligible', 'Not Eligible'), ('pending', 'Pending'), ('approved', 'Approved'), ('transferred', 'Transferred')], default='not_eligible', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='protect_registry', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='LocationAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('authorised', 'Authorised'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='requested', max_length=20)),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protect_location_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protect_location_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_request_id', models.CharField(blank=True, max_length=100)),
                ('result_status', models.CharField(default='pending', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_metres', models.PositiveIntegerField(blank=True, null=True)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='protect.locationaccesssession')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('case_type', models.CharField(choices=[('lost', 'Lost device'), ('stolen', 'Stolen device')], max_length=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_investigation', 'Under Investigation'), ('awaiting_police_report', 'Awaiting Police Report'), ('awaiting_approval', 'Awaiting Approval'), ('recovery_active', 'Recovery Active'), ('recovered', 'Recovered'), ('cancelled', 'Cancelled'), ('closed_not_recovered', 'Closed Not Recovered'), ('closed_recovered', 'Closed Recovered')], db_index=True, default='new', max_length=30)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_location', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('police_station', models.CharField(blank=True, max_length=150)),
                ('police_reference', models.CharField(blank=True, max_length=100)),
                ('alternative_phone', models.CharField(max_length=30)),
                ('alternative_contact_name', models.CharField(blank=True, max_length=150)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protect_cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protect_cases_opened', to=settings.AUTH_USER_MODEL)),
                ('registry_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='protect.deviceregistryentry')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, max_length=60)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_reference', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='protect.protectcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='locationaccesssession',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_sessions', to='protect.protectcase'),
        ),
        migrations.CreateModel(
            name='ProtectConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=30)),
                ('text_snapshot', models.TextField()),
                ('authentication_method', models.CharField(max_length=30)),
                ('authenticated_reference', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consent', to='protect.protectcase')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('police_report', 'Police Report'), ('legal_authority', 'Legal Authority'), ('recovery_evidence', 'Recovery Evidence')], max_length=30)),
                ('file', models.FileField(upload_to='protect/documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='protect.protectcase')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_type', models.CharField(choices=[('ownership', 'Ownership'), ('stolen_report', 'Stolen Report'), ('recovery', 'Recovery'), ('financing_completion', 'Financing Completion')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('verification_token', models.CharField(default=protect.models.verification_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked'), ('superseded', 'Superseded')], default='valid', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='protect.devicecertificate')),
                ('registry_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='protect.deviceregistryentry')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='protect.protectcase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registry_entry', 'certificate_type', 'version'), name='unique_protect_certificate_version')],
            },
        ),
    ]
