from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path("home/", views.home, name="home"),
    path("home/", views.home, name="home_redirect"),
    path("merchant/", RedirectView.as_view(pattern_name="merchant_dashboard", permanent=False), name="merchant_shortcut"),
    path("underwriter/", RedirectView.as_view(pattern_name="underwriter_dashboard", permanent=False), name="underwriter_shortcut"),
    path("hq/", RedirectView.as_view(pattern_name="hq_dashboard", permanent=False), name="hq_shortcut"),
    path("tengasale/merchant/", views.merchant_dashboard, name="merchant_dashboard"),

    # ── HQ routes ──────────────────────────────────────────────────────────────
    path("tengasale/hq/", views.hq_dashboard, name="hq_dashboard"),
    path("tengasale/hq/users/", views.hq_users, name="hq_users"),
    path("tengasale/hq/users/<int:user_id>/", views.hq_user_edit, name="hq_user_edit"),
    path("tengasale/hq/deals/", views.hq_deals, name="hq_deals"),
    path("tengasale/hq/applications/", views.hq_applications, name="hq_applications"),
    path("tengasale/hq/underwriter-queue/", views.hq_underwriter_queue, name="hq_underwriter_queue"),
    path("tengasale/hq/commissions/", views.hq_commissions, name="hq_commissions"),
    path("tengasale/hq/commission-ledger/", views.hq_commission_ledger, name="hq_commission_ledger"),
    path("tengasale/hq/merchant-payouts/", views.hq_merchant_payouts, name="hq_merchant_payouts"),
    path("tengasale/hq/reports/", views.hq_reports, name="hq_reports"),
    path("tengasale/hq/portfolio/", views.hq_portfolio, name="hq_portfolio"),
    path("tengasale/hq/portfolio/investor-report/", views.hq_portfolio_investor_report, name="hq_portfolio_investor_report"),
    path("tengasale/hq/portfolio/export.csv", views.hq_portfolio_export_csv, name="hq_portfolio_export_csv"),
    path("tengasale/hq/portfolio/export.xls", views.hq_portfolio_export_excel, name="hq_portfolio_export_excel"),
    path("tengasale/hq/portfolio/export.pdf", views.hq_portfolio_export_pdf, name="hq_portfolio_export_pdf"),
    path("tengasale/hq/staff-dashboard/", views.staff_dashboard, name="staff_dashboard"),
    path("tengasale/hq/volts/", views.hq_volts_engine, name="hq_volts_engine"),
    path("tengasale/hq/volts/<int:transaction_id>/action/", views.hq_volts_action, name="hq_volts_action"),
    path("tengasale/hq/founder-equity/", views.hq_founder_equity, name="hq_founder_equity"),
    path("tengasale/hq/staff-roles/", views.hq_staff_roles, name="hq_staff_roles"),
    path("tengasale/hq/discipline/", views.hq_discipline_governance, name="hq_discipline_governance"),
    path("tengasale/hq/discipline/<int:period_id>/action/", views.hq_discipline_action, name="hq_discipline_action"),
    path("tengasale/hq/kpis/", views.hq_kpi_dashboard, name="hq_kpi_dashboard"),
    path("tengasale/hq/payout-approvals/", views.hq_payout_approvals, name="hq_payout_approvals"),
    path("tengasale/hq/staff-documents/", views.hq_staff_documents, name="hq_staff_documents"),
    path("tengasale/hq/staff-documents/<int:user_id>/<str:document_type>.pdf", views.staff_document_pdf, name="staff_document_pdf"),
    path("tengasale/hq/discipline/<int:period_id>/acknowledge/", views.staff_discipline_acknowledge, name="staff_discipline_acknowledge"),
    path("tengasale/hq/discipline/<int:period_id>/dispute/", views.staff_discipline_dispute, name="staff_discipline_dispute"),
    path("tengasale/hq/simulations/", views.hq_simulations, name="hq_simulations"),
    path("tengasale/hq/operations/", views.hq_operations, name="hq_operations"),
    path("tengasale/hq/safe-operations/", views.hq_safe_operations, name="hq_safe_operations"),
    path("tengasale/hq/devices/", views.hq_devices, name="hq_devices"),
    path("tengasale/hq/repossession-resale/", views.hq_repossession_resale, name="hq_repossession_resale"),
    path("tengasale/hq/staff-payouts/", views.hq_staff_payouts, name="hq_staff_payouts"),
    path("tengasale/hq/auto-approval/", views.hq_auto_approval, name="hq_auto_approval"),
    path("tengasale/hq/payment-collections/", views.hq_payment_collections, name="hq_payment_collections"),
    path("tengasale/hq/reconciliation/", views.hq_reconciliation, name="hq_reconciliation"),
    path("tengasale/hq/sales-analytics/", views.hq_sales_analytics, name="hq_sales_analytics"),
    path("tengasale/hq/underwriter-performance/", views.hq_underwriter_performance, name="hq_underwriter_performance"),
    path("tengasale/hq/qc/call-recordings/", views.hq_call_recording_qc, name="hq_call_recording_qc"),
    path("tengasale/hq/qc/call-recordings/<int:recording_id>/action/", views.hq_call_recording_qc_action, name="hq_call_recording_qc_action"),
    path("tengasale/hq/qc/penalties/<int:penalty_id>/reverse/", views.hq_qc_penalty_reverse, name="hq_qc_penalty_reverse"),
    path("tengasale/hq/fraud-checks/", views.hq_fraud_checks, name="hq_fraud_checks"),
    path("tengasale/hq/audit-trail/", views.hq_audit_trail, name="hq_audit_trail"),
    path("tengasale/hq/payment-intelligence/", views.hq_payment_intelligence, name="hq_payment_intelligence"),
    path("tengasale/hq/preview/merchant/", views.hq_merchant_preview, name="hq_merchant_preview"),
    path("tengasale/hq/preview/underwriter/", views.hq_underwriter_preview, name="hq_underwriter_preview"),
    path("tengasale/hq/merchant-agreements/", views.hq_merchant_agreements, name="hq_merchant_agreements"),
    path("tengasale/hq/merchant-agreements/<int:agreement_id>/require-resign/", views.hq_agreement_require_resign, name="hq_agreement_require_resign"),
    path("tengasale/hq/merchant-agreements/<int:agreement_id>/pdf/", views.hq_agreement_pdf, name="hq_agreement_pdf"),

    # ── Short /hq/ aliases ─────────────────────────────────────────────────────
    path("hq/", RedirectView.as_view(pattern_name="hq_dashboard", permanent=False), name="hq_alias"),
    path("hq/commissions/", RedirectView.as_view(pattern_name="hq_commissions", permanent=False), name="hq_commissions_alias"),
    path("hq/commission-ledger/", RedirectView.as_view(pattern_name="hq_commission_ledger", permanent=False), name="hq_commission_ledger_alias"),
    path("hq/merchant-payouts/", RedirectView.as_view(pattern_name="hq_merchant_payouts", permanent=False), name="hq_merchant_payouts_alias"),
    path("hq/reports/", RedirectView.as_view(pattern_name="hq_reports", permanent=False), name="hq_reports_alias"),
    path("hq/portfolio/", RedirectView.as_view(pattern_name="hq_portfolio", permanent=False), name="hq_portfolio_alias"),
    path("hq/portfolio/investor-report/", RedirectView.as_view(pattern_name="hq_portfolio_investor_report", permanent=False), name="hq_portfolio_investor_report_alias"),
    path("hq/portfolio/export.csv", RedirectView.as_view(pattern_name="hq_portfolio_export_csv", permanent=False), name="hq_portfolio_export_csv_alias"),
    path("hq/portfolio/export.xls", RedirectView.as_view(pattern_name="hq_portfolio_export_excel", permanent=False), name="hq_portfolio_export_excel_alias"),
    path("hq/portfolio/export.pdf", RedirectView.as_view(pattern_name="hq_portfolio_export_pdf", permanent=False), name="hq_portfolio_export_pdf_alias"),
    path("hq/staff-dashboard/", RedirectView.as_view(pattern_name="staff_dashboard", permanent=False), name="staff_dashboard_alias"),
    path("hq/volts/", RedirectView.as_view(pattern_name="hq_volts_engine", permanent=False), name="hq_volts_engine_alias"),
    path("hq/founder-equity/", RedirectView.as_view(pattern_name="hq_founder_equity", permanent=False), name="hq_founder_equity_alias"),
    path("hq/staff-roles/", RedirectView.as_view(pattern_name="hq_staff_roles", permanent=False), name="hq_staff_roles_alias"),
    path("hq/discipline/", RedirectView.as_view(pattern_name="hq_discipline_governance", permanent=False), name="hq_discipline_governance_alias"),
    path("hq/kpis/", RedirectView.as_view(pattern_name="hq_kpi_dashboard", permanent=False), name="hq_kpi_dashboard_alias"),
    path("hq/payout-approvals/", RedirectView.as_view(pattern_name="hq_payout_approvals", permanent=False), name="hq_payout_approvals_alias"),
    path("hq/staff-documents/", RedirectView.as_view(pattern_name="hq_staff_documents", permanent=False), name="hq_staff_documents_alias"),
    path("hq/simulations/", RedirectView.as_view(pattern_name="hq_simulations", permanent=False), name="hq_simulations_alias"),
    path("hq/operations/", RedirectView.as_view(pattern_name="hq_operations", permanent=False), name="hq_operations_alias"),
    path("hq/safe-operations/", RedirectView.as_view(pattern_name="hq_safe_operations", permanent=False), name="hq_safe_operations_alias"),
    path("hq/devices/", RedirectView.as_view(pattern_name="hq_devices", permanent=False), name="hq_devices_alias"),
    path("hq/repossession-resale/", RedirectView.as_view(pattern_name="hq_repossession_resale", permanent=False), name="hq_repossession_resale_alias"),
    path("hq/staff-payouts/", RedirectView.as_view(pattern_name="hq_staff_payouts", permanent=False), name="hq_staff_payouts_alias"),
    path("hq/auto-approval/", RedirectView.as_view(pattern_name="hq_auto_approval", permanent=False), name="hq_auto_approval_alias"),
    path("hq/qc/call-recordings/", RedirectView.as_view(pattern_name="hq_call_recording_qc", permanent=False), name="hq_call_recording_qc_alias"),
]
