# Generated by Django 6.0.5 on 2026-05-31 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0015_alter_financingapplication_gender"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLockPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("grace_period_days", models.PositiveIntegerField(default=3)),
                ("lock_after_days_overdue", models.PositiveIntegerField(default=7)),
                ("unlock_when_paid_to_date", models.BooleanField(default=True)),
                ("release_when_contract_completed", models.BooleanField(default=True)),
                ("allow_manual_override", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device Lock Policy",
                "verbose_name_plural": "Device Lock Policies",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLockProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=150)),
                ("customer_phone", models.CharField(blank=True, max_length=30)),
                ("imei", models.CharField(db_index=True, max_length=20)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("deal_name", models.CharField(blank=True, max_length=200)),
                (
                    "lock_provider",
                    models.CharField(
                        choices=[
                            ("none", "None (no lock provider)"),
                            ("mock", "Mock (demo/test)"),
                            ("samsung_knox", "Samsung Knox"),
                            ("trustonic", "Trustonic"),
                            ("paytrigger", "PayTrigger"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "provider_device_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "provider_enrollment_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "provider_contract_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lock_status",
                    models.CharField(
                        choices=[
                            ("not_enrolled", "Not Enrolled"),
                            ("enrollment_pending", "Enrollment Pending"),
                            ("enrolled", "Enrolled"),
                            ("active", "Active"),
                            ("lock_pending", "Lock Pending"),
                            ("locked", "Locked"),
                            ("unlock_pending", "Unlock Pending"),
                            ("unlocked", "Unlocked"),
                            ("released", "Released"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="not_enrolled",
                        max_length=25,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_lock_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_unlock_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("is_lockable", models.BooleanField(default=False)),
                ("is_released", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_lock_profile",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_lock_profile",
                        to="contracts.contract",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_lock_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="device_lock.devicelockpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Lock Profile",
                "verbose_name_plural": "Device Lock Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("enroll_requested", "Enroll Requested"),
                            ("enroll_success", "Enroll Success"),
                            ("enroll_failed", "Enroll Failed"),
                            ("lock_requested", "Lock Requested"),
                            ("lock_success", "Lock Success"),
                            ("lock_failed", "Lock Failed"),
                            ("unlock_requested", "Unlock Requested"),
                            ("unlock_success", "Unlock Success"),
                            ("unlock_failed", "Unlock Failed"),
                            ("release_requested", "Release Requested"),
                            ("release_success", "Release Success"),
                            ("release_failed", "Release Failed"),
                            ("status_sync", "Status Sync"),
                            ("webhook_received", "Webhook Received"),
                            ("manual_override", "Manual Override"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("status_before", models.CharField(blank=True, max_length=25)),
                ("status_after", models.CharField(blank=True, max_length=25)),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("admin", "Admin"),
                            ("underwriter", "Underwriter"),
                            ("merchant", "Merchant"),
                            ("repayment_engine", "Repayment Engine"),
                            ("webhook", "Webhook"),
                            ("management_command", "Management Command"),
                        ],
                        default="system",
                        max_length=25,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_lock_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lock_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="device_lock.devicelockprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Lock Event",
                "verbose_name_plural": "Device Lock Events",
                "ordering": ["-created_at"],
            },
        ),
    ]
