# Generated by Django 6.0.5 on 2026-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_hq_deal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedeal",
            name="catalog_source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("used", "Used"),
                    ("refurbished", "Refurbished"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="is_lock_ready",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="popularity_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
