# Generated by Django 6.0.5 on 2026-06-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_devicedeal_catalog_source_devicedeal_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedeal',
            name='unlock_days',
            field=models.PositiveIntegerField(default=14, help_text='Number of days of device access granted by the deposit payment.'),
        ),
    ]
