# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0006_update_unlock_days_default_14"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedeal",
            name="unlock_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Number of days of device access granted by the deposit payment.",
            ),
        ),
    ]
