# Generated by Django 6.0.5 on 2026-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_update_unlock_days_default_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedeal',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Approved, model-specific product image shown on the public phone catalogue.', null=True, upload_to='device_images/'),
        ),
        migrations.AddField(
            model_name='devicedeal',
            name='product_image_alt',
            field=models.CharField(blank=True, help_text='Accessible description, for example: Tecno Spark 40 in black, front and rear view.', max_length=180),
        ),
    ]
