# Generated by Django 6.0.5 on 2026-06-08 20:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0003_merchantpayout_deposit_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('payout_phone', models.CharField(blank=True, max_length=20)),
                ('confirmed', models.BooleanField(default=False, help_text='Requester confirmed understanding of 20% emergency payout rule.')),
                ('earned_this_month_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('emergency_limit_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('already_requested_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending HQ Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_provider', models.CharField(blank=True, max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emergency_payouts', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_payout_requests', to='earnings.wallet')),
            ],
            options={
                'verbose_name': 'Emergency Payout Request',
                'verbose_name_plural': 'Emergency Payout Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
