# Generated by Django 6.0.5 on 2026-08-09 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0005_earningssecurityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningssecurityevent',
            name='event_type',
            field=models.CharField(choices=[('EARNINGS_LOCK_ENABLED', 'Earnings lock enabled'), ('EARNINGS_LOCK_DISABLED', 'Earnings lock disabled'), ('EARNINGS_UNLOCK_SUCCESS', 'Earnings unlock succeeded'), ('EARNINGS_UNLOCK_FAILED', 'Earnings unlock failed'), ('EARNINGS_PIN_CHANGED', 'Earnings PIN changed'), ('EARNINGS_PIN_RESET', 'Earnings PIN reset'), ('EARNINGS_LOCKOUT_TRIGGERED', 'Earnings lockout triggered'), ('EARNINGS_RECOVERY_STARTED', 'Owner recovery started'), ('EARNINGS_RECOVERY_COMPLETED', 'Owner recovery completed'), ('PAYOUT_REAUTHENTICATED', 'Payout reauthenticated')], max_length=40),
        ),
        migrations.CreateModel(
            name='EarningsRecoveryChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('enable', 'Enable lock'), ('reset', 'Reset PIN'), ('disable', 'Disable lock')], max_length=12)),
                ('code_hash', models.CharField(editable=False, max_length=255)),
                ('phone_mask', models.CharField(max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_recovery_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='earn_recovery_lookup_idx')],
            },
        ),
    ]
