# Generated by Django 6.0.5 on 2026-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0006_earningsrecoverychallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningssecurityevent',
            name='event_type',
            field=models.CharField(choices=[('EARNINGS_LOCK_ENABLED', 'Earnings lock enabled'), ('EARNINGS_LOCK_DISABLED', 'Earnings lock disabled'), ('EARNINGS_UNLOCK_SUCCESS', 'Earnings unlock succeeded'), ('EARNINGS_UNLOCK_FAILED', 'Earnings unlock failed'), ('EARNINGS_PIN_CHANGED', 'Earnings PIN changed'), ('EARNINGS_PIN_RESET', 'Earnings PIN reset'), ('EARNINGS_RATE_LIMITED', 'Earnings access rate limited'), ('EARNINGS_RECOVERY_STARTED', 'Owner recovery started'), ('EARNINGS_RECOVERY_COMPLETED', 'Owner recovery completed'), ('PAYOUT_REAUTH_SUCCESS', 'Payout PIN reauthentication succeeded')], max_length=40),
        ),
    ]
