# Generated by Django 6.0.5 on 2026-06-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_merchantcontractpayout_commissionledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantcontractpayout',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchantcontractpayout',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchantcontractpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('held', 'Held'), ('disputed', 'Disputed'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
