# Generated by Django 6.0.5 on 2026-06-13 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_didit_manual_override_audit'),
        ('device_lock', '0001_initial'),
        ('portal', '0014_alter_paymenttransaction_status'),
        ('risk', '0003_add_fraudcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnectivitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('merchant_name', models.CharField(blank=True, max_length=150)),
                ('underwriter_name', models.CharField(blank=True, max_length=150)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(choices=[('paytrigger', 'PayTrigger'), ('upya', 'Upya'), ('manual', 'Manual Entry'), ('mock', 'Mock / Placeholder')], default='mock', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_source', models.CharField(blank=True, max_length=80)),
                ('days_offline', models.IntegerField(default=0, help_text='Computed or manually entered days since last seen online')),
                ('lock_state', models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('locked', 'Locked'), ('released', 'Released'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('sim_changed', models.BooleanField(blank=True, null=True)),
                ('location_changed', models.BooleanField(blank=True, null=True)),
                ('repeated_failed_lock_attempts', models.IntegerField(default=0)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('arrears_days', models.IntegerField(default=0)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_unlock_request_at', models.DateTimeField(blank=True, null=True)),
                ('last_lock_command_at', models.DateTimeField(blank=True, null=True)),
                ('pending_command_type', models.CharField(choices=[('lock', 'Lock'), ('unlock', 'Unlock'), ('none', 'None')], default='none', max_length=10)),
                ('pending_command_age_hours', models.IntegerField(default=0, help_text='Hours since last pending command was issued')),
                ('connectivity_status', models.CharField(choices=[('recently_online', 'Recently Online'), ('offline_paid', 'Offline — Paid Up'), ('offline_arrears', 'Offline — With Arrears'), ('offline_after_unlock', 'Offline After Unlock Request'), ('offline_after_payment', 'Offline After Payment'), ('offline_before_lock', 'Offline Before Lock Command'), ('offline_after_lock', 'Offline After Lock Command'), ('sync_pending', 'Sync Pending'), ('needs_internet', 'Customer Needs Internet Connection'), ('possible_evasion', 'Possible Evasion — Needs Review'), ('recovery_review', 'Recovery Review Required'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending_device_online', 'Pending — Device Must Come Online'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('connectivity_help_needed', models.BooleanField(default=False, help_text='True when device needs to come online before a command can sync')),
                ('risk_band', models.CharField(choices=[('normal', 'Normal'), ('watch', 'Watch'), ('warning', 'Warning'), ('high', 'High Risk'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='0–100 composite risk score (higher = more risk)')),
                ('support_priority', models.IntegerField(default=0, help_text='0–100 support priority score (higher = needs more attention)')),
                ('recommended_action', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('sync_instruction_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectivity_signals', to='applications.financingapplication')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectivity_signals', to='portal.paymentcontract')),
                ('false_positive_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='false_positive_signals', to=settings.AUTH_USER_MODEL)),
                ('lock_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectivity_signals', to='device_lock.devicelockprofile')),
            ],
            options={
                'verbose_name': 'Device Connectivity Signal',
                'verbose_name_plural': 'Device Connectivity Signals',
                'ordering': ['-risk_score', '-days_offline', '-created_at'],
            },
        ),
    ]
