# Generated by Django 6.0.5 on 2026-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_add_source_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_average_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_avg_interval_days",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Average days between payments", null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_consistency",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Payment consistency 0–100 (days covered / days since start)",
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_days_late",
            field=models.PositiveIntegerField(
                default=0, help_text="Total days currently behind schedule"
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_discipline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Excellent / Good / Fair / Needs Improvement",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_largest_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_payment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_preferred_day",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Day-of-week customer most often pays",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_preferred_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Most-used payment provider",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_smallest_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="analytics_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
