# Generated by Django 6.0.5 on 2026-06-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_payg_upgrade"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="paymentcontract",
            name="portal_paym_payg_nu_b92f51_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentcontract",
            new_name="portal_paym_imei_nu_d83359_idx",
            old_name="portal_paym_imei_nu_idx",
        ),
    ]
