# Generated by Django 6.0.5 on 2026-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0007_remove_paymentcontract_portal_paym_payg_nu_b92f51_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="balance_after",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Contract balance after this payment was applied",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="balance_before",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Contract balance before this payment was applied",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="charge_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PayChangu MoMo charge_id (used for verification calls)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="initiated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the payment was first initiated with the provider",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("airtel", "Airtel Money"),
                    ("tnm", "TNM Mpamba"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Mobile money network used: airtel, tnm, or other",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="raw_request",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw payload sent to payment provider",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="webhook_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw payload received from provider webhook",
            ),
        ),
    ]
