# Generated by Django 6.0.5 on 2026-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_payg_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcontract',
            name='deposit_access_days',
            field=models.PositiveIntegerField(default=14, help_text='Days of device access unlocked by the deposit payment.'),
        ),
    ]
