# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_add_deposit_access_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcontract",
            name="deposit_access_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Days of device access unlocked by the deposit payment.",
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="access_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="deposit_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="deposit_unlock_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="last_payment_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
