# Generated by Django 6.0.5 on 2026-06-06 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_paymentcontract_access_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcontract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('locked', 'Locked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('repossession_pending', 'Repossession Pending'), ('repossessed', 'Repossessed'), ('ready_for_resale', 'Ready for Resale'), ('resold', 'Resold'), ('written_off', 'Written Off / Shortfall'), ('legally_closed', 'Legally Closed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='RecoveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('repossession', 'Repossession'), ('tracing', 'Tracing'), ('legal', 'Legal'), ('storage', 'Storage'), ('repair', 'Repair'), ('resale', 'Resale'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('incurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='recovery_costs/evidence/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_chargeable_to_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recovery_costs', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_costs', to='portal.paymentcontract')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_recovery_costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_at', '-created_at'],
                'indexes': [models.Index(fields=['contract', 'approved_at'], name='portal_reco_contrac_3645d1_idx'), models.Index(fields=['cost_type', 'incurred_at'], name='portal_reco_cost_ty_e0b197_idx')],
            },
        ),
    ]
