# Generated by Django 6.0.5 on 2026-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_paymentcontract_status_recoverycost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('tenga_processing', 'TengaSale Processing'), ('external_processing', 'External Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
