# Generated by Django 6.0.5 on 2026-06-01 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("app_submitted", "Application Submitted"),
                            ("app_sent_back", "Application Sent Back"),
                            ("app_approved", "Application Approved"),
                            ("app_rejected", "Application Rejected"),
                            ("terms_pending", "Awaiting Terms Review"),
                            ("ready_activation", "Ready for Activation"),
                            ("app_activated", "Contract Activated"),
                            ("app_completed", "Contract Completed"),
                            ("app_defaulted", "Contract Defaulted"),
                            ("new_application", "New Application"),
                            ("assigned", "Application Assigned"),
                            ("resubmission", "Application Resubmitted"),
                            ("sla_warning", "SLA Warning"),
                            ("high_risk", "High Risk Application"),
                            ("imei_mismatch", "IMEI Mismatch"),
                            ("warranty_failure", "Warranty Check Failure"),
                            ("high_exposure", "High Exposure"),
                            ("default_risk", "Default Risk"),
                            ("system_error", "System Error"),
                            ("app_update", "App Update"),
                            ("maintenance", "Maintenance Notice"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("object_type", models.CharField(blank=True, max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means broadcast to all users",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_86ea8b_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                ],
            },
        ),
    ]
