# Generated by Django 6.0.5 on 2026-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('app_submitted', 'Application Submitted'), ('app_sent_back', 'Application Sent Back'), ('app_approved', 'Application Approved'), ('app_rejected', 'Application Rejected'), ('terms_pending', 'Awaiting Terms Review'), ('ready_activation', 'Ready for Activation'), ('app_activated', 'Contract Activated'), ('app_completed', 'Contract Completed'), ('app_defaulted', 'Contract Defaulted'), ('new_application', 'New Application'), ('assigned', 'Application Assigned'), ('resubmission', 'Application Resubmitted'), ('sla_warning', 'SLA Warning'), ('high_risk', 'High Risk Application'), ('imei_mismatch', 'IMEI Mismatch'), ('warranty_failure', 'Warranty Check Failure'), ('high_exposure', 'High Exposure'), ('default_risk', 'Default Risk'), ('system_error', 'System Error'), ('app_update', 'App Update'), ('maintenance', 'Maintenance Notice'), ('contract_update', 'Contract Update'), ('deposit_paid', 'Deposit Paid'), ('device_locked', 'Device Locked'), ('payment_received', 'Payment Received'), ('customer_overdue', 'Customer Overdue'), ('customer_locked', 'Customer Locked'), ('recovery_update', 'Recovery Update'), ('support_update', 'Support Update')], max_length=40),
        ),
    ]
