# Generated by Django 6.0.5 on 2026-06-06 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('applications', '0020_didit_manual_override_audit'),
        ('contracts', '0004_contract_term_months_contract_terms_confirmed_at_and_more'),
        ('merchants', '0002_merchant_agreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShareStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_authorized_shares', models.PositiveIntegerField(default=100000)),
                ('founder_pool', models.PositiveIntegerField(default=70000)),
                ('investor_reserve', models.PositiveIntegerField(default=20000)),
                ('employee_advisor_pool', models.PositiveIntegerField(default=10000)),
                ('notes', models.TextField(blank=True, default='The app tracks equity and vesting internally, but signed legal documents govern actual ownership.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Share Structure',
                'verbose_name_plural': 'Company Share Structures',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('default_volts_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_ceiling_mwk', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_initials',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_joined_company',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('founder', 'Founder'), ('staff', 'Staff'), ('merchant', 'Merchant'), ('customer', 'Customer'), ('executive', 'Executive')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='FounderEquityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=160)),
                ('allocated_shares', models.PositiveIntegerField()),
                ('vested_shares', models.PositiveIntegerField(default=0)),
                ('unvested_shares', models.PositiveIntegerField(default=0)),
                ('vesting_start_date', models.DateField(blank=True, null=True)),
                ('cliff_date', models.DateField(blank=True, null=True)),
                ('vesting_years', models.PositiveSmallIntegerField(default=4)),
                ('vesting_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('forfeited', 'Forfeited'), ('completed', 'Completed')], default='active', max_length=20)),
                ('inactive_flag', models.BooleanField(default=False)),
                ('breach_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_equity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role_title'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volts_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_penalties', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_transactions', to=settings.AUTH_USER_MODEL)),
                ('penalty_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.penaltytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.rank'),
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('portal_role', models.CharField(choices=[('hq', 'HQ/Admin'), ('merchant_admin', 'Merchant Admin'), ('underwriter', 'Underwriter'), ('merchant', 'Merchant'), ('customer', 'Customer'), ('support', 'Support')], default='hq', max_length=30)),
                ('module_permissions', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_roles', to='accounts.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.staffrole'),
        ),
        migrations.CreateModel(
            name='VoltsActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('base_volts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_approval', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volts_action_types', to='accounts.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoltsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_volts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('discipline_score', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('results_score', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('final_volts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monetary_value_per_volt', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('estimated_amount_mwk', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='volts_evidence/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.voltsactiontype')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_volts_transactions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volts_transactions', to='accounts.department')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volts_transactions', to='applications.financingapplication')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volts_transactions', to='contracts.contract')),
                ('related_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volts_transactions', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volts_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='accounts_vo_user_id_5c4a58_idx'), models.Index(fields=['department', 'status', 'created_at'], name='accounts_vo_departm_300edb_idx')],
            },
        ),
    ]
