# Generated by Django 6.0.5 on 2026-06-07 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_companysharestructure_department_penaltytype_rank_and_more'),
        ('applications', '0020_didit_manual_override_audit'),
        ('contracts', '0004_contract_term_months_contract_terms_confirmed_at_and_more'),
        ('merchants', '0002_merchant_agreement'),
        ('portal', '0014_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('start_day', models.PositiveSmallIntegerField(default=25)),
                ('end_day', models.PositiveSmallIntegerField(default=24)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('code', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('evidence_required', models.BooleanField(default=False)),
                ('auto_generated', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='rank',
            name='base_salary_default_mwk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rank',
            name='is_board_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rank',
            name='rank_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='rank',
            name='volt_rate_default_mwk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_salary_mwk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_discipline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_payouts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_volts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_override_scores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='founder_equity_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_record', to='accounts.founderequityrecord'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_ceiling_mwk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='probation_status',
            field=models.CharField(choices=[('none', 'None'), ('active', 'On probation'), ('passed', 'Passed'), ('extended', 'Extended'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volt_rate_mwk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='voltsactiontype',
            name='code',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='voltstransaction',
            name='ceiling_adjustment_mwk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='voltstransaction',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volts_transactions', to='portal.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='voltstransaction',
            name='related_task_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='DisciplineScorePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('opening_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('automatic_penalties_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('manual_adjustments_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bonus_points_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('final_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('reviewed', 'Reviewed'), ('disputed', 'Disputed'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payout_impact_approved_at', models.DateTimeField(blank=True, null=True)),
                ('user_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user_response_text', models.TextField(blank=True)),
                ('dispute_status', models.CharField(choices=[('none', 'None'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='none', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discipline_periods', to=settings.AUTH_USER_MODEL)),
                ('payout_impact_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_approved_discipline_periods', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_discipline_periods', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_score_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('automatic', 'Automatic'), ('manager', 'Manager'), ('audit', 'Audit'), ('qc', 'QC'), ('customer_support', 'Customer Support'), ('finance', 'Finance'), ('legal', 'Legal')], default='manager', max_length=30)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='discipline_evidence/')),
                ('related_task_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discipline_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discipline_events', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_events', to='applications.financingapplication')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_events', to='contracts.contract')),
                ('related_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_events', to='merchants.merchant')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_events', to='portal.paymenttransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_discipline_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_events', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounts.disciplineeventtype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.disciplinescoreperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_text', models.TextField()),
                ('supporting_file', models.FileField(blank=True, null=True, upload_to='discipline_disputes/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('partially_accepted', 'Partially accepted'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='submitted', max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_discipline_disputes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_disputes', to=settings.AUTH_USER_MODEL)),
                ('discipline_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='accounts.disciplineevent')),
                ('discipline_score_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='accounts.disciplinescoreperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('lower_is_better', models.BooleanField(default=False)),
                ('data_source', models.CharField(blank=True, max_length=120)),
                ('affects_quality_score', models.BooleanField(default=False)),
                ('affects_discipline_score', models.BooleanField(default=False)),
                ('affects_results_score', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_templates', to='accounts.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_templates', to='accounts.staffrole')),
            ],
            options={
                'ordering': ['department__name', 'role__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('evidence', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kpi_results', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kpi_results', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_results', to=settings.AUTH_USER_MODEL)),
                ('kpi_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='accounts.kpitemplate')),
            ],
            options={
                'ordering': ['-period', 'user__username', 'kpi_template__name'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('employment_agreement', 'Employment Agreement'), ('compensation_annexure_a', 'Compensation Annexure A'), ('kpi_volts_annexure_b', 'KPI & Volts Annexure B'), ('monthly_volts_statement', 'Monthly Volts Statement'), ('monthly_performance_review', 'Monthly Performance Review'), ('discipline_score_report', 'Discipline Score Report'), ('promotion_rank_review', 'Promotion/Rank Review'), ('warning_letter', 'Warning Letter'), ('termination_letter', 'Termination Letter')], max_length=40)),
                ('document_number', models.CharField(max_length=80, unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_staff_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disciplinescoreperiod',
            index=models.Index(fields=['user', 'month', 'status'], name='accounts_di_user_id_f4aa9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinescoreperiod',
            unique_together={('user', 'month')},
        ),
        migrations.AddIndex(
            model_name='disciplineevent',
            index=models.Index(fields=['user', 'status', 'created_at'], name='accounts_di_user_id_9a09ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpitemplate',
            unique_together={('role', 'department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kpiresult',
            unique_together={('user', 'kpi_template', 'period')},
        ),
    ]
