# Generated by Django 6.0.5 on 2026-06-08 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_compensationcycle_disciplineeventtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocument',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_staff_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending CEO Signature'), ('signed', 'Signed'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='document_type',
            field=models.CharField(choices=[('employment_agreement', 'Employment Agreement'), ('compensation_annexure_a', 'Compensation Annexure A'), ('kpi_volts_annexure_b', 'KPI & Volts Annexure B'), ('monthly_volts_statement', 'Monthly Volts Statement'), ('monthly_performance_review', 'Monthly Performance Review'), ('discipline_score_report', 'Discipline Score Report'), ('promotion_rank_review', 'Promotion/Rank Review'), ('warning_letter', 'Warning Letter'), ('termination_letter', 'Termination Letter'), ('suspension_letter', 'Suspension Letter'), ('appointment_letter', 'Appointment Letter'), ('confidentiality_agreement', 'Confidentiality & Data Protection Agreement'), ('role_responsibility_schedule', 'Role Responsibility Schedule')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExecutiveSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(default='Chief Executive Officer', max_length=200)),
                ('signature_image', models.ImageField(help_text='PNG/JPG of the handwritten or digital signature.', upload_to='signatures/executive/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active signature should exist at a time per position.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_uploads', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_revocations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The executive whose signature this is.', on_delete=django.db.models.deletion.PROTECT, related_name='executive_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive Signature',
                'verbose_name_plural': 'Executive Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='used_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_documents', to='accounts.executivesignature'),
        ),
    ]
