# Generated by Django 6.0.5 on 2026-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_earnings_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='earnings_access',
            field=models.BooleanField(default=True, help_text='Role permission to view protected earnings surfaces.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earnings_recovery_phone',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earnings_recovery_verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earnings_relock_minutes',
            field=models.PositiveSmallIntegerField(choices=[(0, 'When leaving Earnings'), (1, 'After 1 minute'), (5, 'After 5 minutes'), (15, 'After 15 minutes')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earnings_security_generation',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
