# Generated by Django 6.0.5 on 2026-06-03 21:09

import communications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0017_financingapplication_phone_verification_status_and_more'),
        ('contracts', '0004_contract_term_months_contract_terms_confirmed_at_and_more'),
        ('portal', '0010_payg_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('otp_code', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=communications.models.default_otp_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_otps', to='applications.financingapplication')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('payment_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.paymentcontract')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='communicati_phone_n_41e62e_idx'), models.Index(fields=['is_verified', 'expires_at'], name='communicati_is_veri_0acf35_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('purpose', models.CharField(choices=[('payment_confirmation', 'Payment Confirmation'), ('otp', 'OTP'), ('due_reminder', 'Due Reminder'), ('payment_due_today', 'Payment Due Today'), ('arrears_reminder', 'Arrears Reminder'), ('general', 'General')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('pending_config', 'Pending Config')], default='queued', max_length=30)),
                ('provider', models.CharField(default='twilio', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='ny', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='applications.financingapplication')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='contracts.contract')),
                ('payment_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='portal.paymentcontract')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='portal.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='communicati_phone_n_e3bb27_idx'), models.Index(fields=['purpose', 'status'], name='communicati_purpose_95997b_idx'), models.Index(fields=['created_at'], name='communicati_created_e6a22c_idx')],
            },
        ),
    ]
