"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import sys

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file():
    """Load tengasale/.env for local development (does not override existing env vars)."""
    env_path = BASE_DIR / ".env"
    if not env_path.is_file():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_local_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-3mtl0z7s^6z9g$yac8tv*(^($um4o=592tmtrym6o&33**xjo^",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Base settings are local-development friendly; production uses settings_production.py,
# which forces DEBUG=False and keeps manifest static storage enabled.
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
    "tengasale.emajinet.africa",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://tengasale.emajinet.africa",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "accounts.apps.AccountsConfig",
    "merchants",
    "core",
    "geography",
    "applications",
    "deals",
    "earnings",
    "commissions",
    "rewards",
    "approvals",
    "contracts",
    "financing",
    "risk",
    "dashboard",
    "sales",
    "portal",
    "website",
    "merchant_admin.apps.MerchantAdminConfig",
    "support.apps.SupportConfig",
    "device_lock.apps.DeviceLockConfig",
    "notifications.apps.NotificationsConfig",
    "communications.apps.CommunicationsConfig",
    "payments.apps.PaymentsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.tengasale_support",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Blantyre"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

_TESTING = "test" in sys.argv or "pytest" in sys.modules


def _build_storages(*, debug: bool, testing: bool) -> dict:
    # In development or test runs, serve source static files directly; production
    # uses WhiteNoise's compressed manifest storage for hashed assets.
    staticfiles_backend = (
        "django.contrib.staticfiles.storage.StaticFilesStorage"
        if debug or testing
        else "whitenoise.storage.CompressedManifestStaticFilesStorage"
    )
    return {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": staticfiles_backend,
        },
    }


STORAGES = _build_storages(debug=DEBUG, testing=_TESTING)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Cache — use LocMemCache by default (no external dependency needed)
# Upgrade to Redis/Memcached in production for multi-process deployments
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tengasale-default",
        "TIMEOUT": 3600,  # 1 hour default
    }
}

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# ── Email configuration ────────────────────────────────────────────────────────
# Development: console backend (prints to terminal, no real sending).
# Production: set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# in the environment and configure SendGrid SMTP credentials below.
#
# Required env vars for SendGrid production:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST=smtp.sendgrid.net
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=True
#   EMAIL_HOST_USER=apikey
#   EMAIL_HOST_PASSWORD=<your_sendgrid_api_key>
#   DEFAULT_FROM_EMAIL=TengaSale Support <support@tengasale.africa>
#
_email_backend_from_env = os.environ.get("EMAIL_BACKEND", "")
if _email_backend_from_env:
    EMAIL_BACKEND = _email_backend_from_env
elif DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    # In production with no explicit backend, fall back to console to avoid
    # sending nothing silently. Set EMAIL_BACKEND in environment for real mail.
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.sendgrid.net")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "apikey")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")  # SendGrid API key

TENGASALE_WHATSAPP_NUMBER = os.environ.get("TENGASALE_WHATSAPP_NUMBER", "+265883596135")
TENGASALE_WHATSAPP_LINK = f"https://wa.me/{''.join(char for char in TENGASALE_WHATSAPP_NUMBER if char.isdigit())}"

TRUSTONIC_API_KEY = os.environ.get("TRUSTONIC_API_KEY", "")
TRUSTONIC_API_URL = os.environ.get("TRUSTONIC_API_URL", "")
UPYA_API_KEY = os.environ.get("UPYA_API_KEY", "")
UPYA_API_URL = os.environ.get("UPYA_API_URL", "")
PAYMENT_PROVIDER_API_KEY = os.environ.get("PAYMENT_PROVIDER_API_KEY", "")
PAYMENT_PROVIDER_API_URL = os.environ.get("PAYMENT_PROVIDER_API_URL", "")
SMS_PROVIDER_API_KEY = os.environ.get("SMS_PROVIDER_API_KEY", "")
SMS_PROVIDER_API_URL = os.environ.get("SMS_PROVIDER_API_URL", "")

# ── Payment Providers ─────────────────────────────────────────────────────────
MOCK_PAYMENTS = os.environ.get("MOCK_PAYMENTS", "true").lower() == "true"

# PayChangu Mobile Money (Airtel / TNM Mpamba)
PAYCHANGU_PUBLIC_KEY = os.environ.get("PAYCHANGU_PUBLIC_KEY", "")
PAYCHANGU_SECRET_KEY = os.environ.get("PAYCHANGU_SECRET_KEY", "")
PAYCHANGU_WEBHOOK_SECRET = os.environ.get("PAYCHANGU_WEBHOOK_SECRET", "")
PAYCHANGU_API_BASE = os.environ.get("PAYCHANGU_API_BASE", "https://api.paychangu.com")
PAYCHANGU_CALLBACK_URL = os.environ.get("PAYCHANGU_CALLBACK_URL", "")
PAYCHANGU_WEBHOOK_URL = os.environ.get("PAYCHANGU_WEBHOOK_URL", "")
PAYCHANGU_ENVIRONMENT = os.environ.get("PAYCHANGU_ENVIRONMENT", "sandbox")
PAYCHANGU_DEFAULT_CURRENCY = os.environ.get("PAYCHANGU_DEFAULT_CURRENCY", "MWK")
PAYCHANGU_WEBHOOK_DEBUG = os.environ.get("PAYCHANGU_WEBHOOK_DEBUG", "False").lower() in ("true", "1", "yes")

# Operator ref_id overrides (optional; auto-resolved from API if not set)
PAYCHANGU_AIRTEL_REF_ID = os.environ.get("PAYCHANGU_AIRTEL_REF_ID", "")
PAYCHANGU_TNM_REF_ID = os.environ.get("PAYCHANGU_TNM_REF_ID", "")

# Payment mode: "sandbox" | "live"
PAYMENTS_MODE = os.environ.get("PAYMENTS_MODE", "sandbox").lower()

# Safety flags — must be explicitly enabled for real money movement
PAYMENTS_ALLOW_LIVE_CHARGES = os.environ.get("PAYMENTS_ALLOW_LIVE_CHARGES", "false").lower() == "true"
PAYOUTS_ALLOW_LIVE_DISBURSEMENTS = os.environ.get("PAYOUTS_ALLOW_LIVE_DISBURSEMENTS", "false").lower() == "true"

# Direct provider credentials (alternatives to PayChangu)
AIRTEL_MONEY_CLIENT_ID = os.environ.get("AIRTEL_MONEY_CLIENT_ID", "")
AIRTEL_MONEY_CLIENT_SECRET = os.environ.get("AIRTEL_MONEY_CLIENT_SECRET", "")
TNM_MPAMBA_API_KEY = os.environ.get("TNM_MPAMBA_API_KEY", "")
PAYTRIGGER_API_KEY = os.environ.get("PAYTRIGGER_API_KEY", "")

# Direct Airtel Money Malawi API (UAT/live). Keep all values in environment.
def _env_bool(name: str, default: str = "false") -> bool:
    return os.environ.get(name, default).lower() in ("true", "1", "yes", "on")


AIRTEL_ENVIRONMENT = os.environ.get("AIRTEL_ENVIRONMENT", os.environ.get("AIRTEL_ENV", "staging")).lower()
AIRTEL_ENV = os.environ.get("AIRTEL_ENV", AIRTEL_ENVIRONMENT).lower()
AIRTEL_PRODUCTION_ENABLED = _env_bool("AIRTEL_PRODUCTION_ENABLED", "false")
AIRTEL_COLLECTIONS_ENABLED = _env_bool("AIRTEL_COLLECTIONS_ENABLED", "false")
AIRTEL_DRY_RUN = _env_bool("AIRTEL_DRY_RUN", "true")
AIRTEL_TEST_MAX_AMOUNT = os.environ.get("AIRTEL_TEST_MAX_AMOUNT", "1000")
AIRTEL_TEST_MIN_AMOUNT = os.environ.get("AIRTEL_TEST_MIN_AMOUNT", "100")
AIRTEL_ALLOWED_TEST_MSISDNS = os.environ.get("AIRTEL_ALLOWED_TEST_MSISDNS", "")
AIRTEL_BASE_URL = os.environ.get("AIRTEL_BASE_URL", "https://openapiuat.airtel.mw")
AIRTEL_COUNTRY = os.environ.get("AIRTEL_COUNTRY", "MW")
AIRTEL_CURRENCY = os.environ.get("AIRTEL_CURRENCY", "MWK")
AIRTEL_MERCHANT_CODE = os.environ.get("AIRTEL_MERCHANT_CODE", "")
AIRTEL_PRIVATE_KEY = os.environ.get(
    "AIRTEL_PRIVATE_KEY",
    os.environ.get("AIRTEL_CALLBACK_SECRET", os.environ.get("AIRTEL_CALLBACK_HASH_KEY", os.environ.get("AIRTEL_KEY", ""))),
)
AIRTEL_CALLBACK_SECRET = os.environ.get("AIRTEL_CALLBACK_SECRET", "")
AIRTEL_CALLBACK_URL = os.environ.get(
    "AIRTEL_CALLBACK_URL",
    "https://tengasale-api.onrender.com/api/payments/airtel/callback/",
)
AIRTEL_CALLBACK_AUTH_ENABLED = _env_bool("AIRTEL_CALLBACK_AUTH_ENABLED", "true")
AIRTEL_CALLBACK_HASH_KEY = os.environ.get("AIRTEL_CALLBACK_HASH_KEY", AIRTEL_PRIVATE_KEY)
AIRTEL_CLIENT_ID = os.environ.get("AIRTEL_CLIENT_ID", "")
AIRTEL_CLIENT_SECRET = os.environ.get("AIRTEL_CLIENT_SECRET", "")
AIRTEL_AUTH_TOKEN = os.environ.get("AIRTEL_AUTH_TOKEN", "")
AIRTEL_PIN = os.environ.get("AIRTEL_PIN", "")
AIRTEL_MESSAGE_SIGNING_ENABLED = os.environ.get("AIRTEL_MESSAGE_SIGNING_ENABLED", "False").lower() in (
    "true",
    "1",
    "yes",
    "on",
)
AIRTEL_SIGNATURE_SECRET = os.environ.get("AIRTEL_SIGNATURE_SECRET", "")
AIRTEL_KEY = os.environ.get("AIRTEL_KEY", "")
AIRTEL_COLLECTION_PATH = os.environ.get("AIRTEL_COLLECTION_PATH", "/merchant/v1/payments/")
AIRTEL_ENQUIRY_PATH_TEMPLATE = os.environ.get("AIRTEL_ENQUIRY_PATH_TEMPLATE", "/standard/v1/payments/{reference}")
AIRTEL_ENQUIRY_SUPPORTS_MERCHANT_REFERENCE = _env_bool("AIRTEL_ENQUIRY_SUPPORTS_MERCHANT_REFERENCE", "false")
AIRTEL_ALLOW_MERCHANT_REFERENCE_ENQUIRY = _env_bool("AIRTEL_ALLOW_MERCHANT_REFERENCE_ENQUIRY", "false")
AIRTEL_PENDING_RECONCILIATION_MINUTES = int(os.environ.get("AIRTEL_PENDING_RECONCILIATION_MINUTES", "10"))
AIRTEL_ENQUIRY_MIN_INTERVAL_SECONDS = int(os.environ.get("AIRTEL_ENQUIRY_MIN_INTERVAL_SECONDS", "30"))
AIRTEL_ENQUIRY_MAX_ATTEMPTS = int(os.environ.get("AIRTEL_ENQUIRY_MAX_ATTEMPTS", "20"))
AIRTEL_CALLBACK_ALLOWED_SOURCE_IPS = os.environ.get("AIRTEL_CALLBACK_ALLOWED_SOURCE_IPS", "")
AIRTEL_TOKEN_PATH = os.environ.get("AIRTEL_TOKEN_PATH", "/auth/oauth2/token")
AIRTEL_DISBURSEMENT_PATH = os.environ.get("AIRTEL_DISBURSEMENT_PATH", "/standard/v3/disbursements")
AIRTEL_CALLBACK_MAX_BYTES = int(os.environ.get("AIRTEL_CALLBACK_MAX_BYTES", "65536"))
AIRTEL_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("AIRTEL_REQUEST_TIMEOUT_SECONDS", "30"))
AIRTEL_CONNECT_TIMEOUT = int(os.environ.get("AIRTEL_CONNECT_TIMEOUT", "5"))
AIRTEL_READ_TIMEOUT = int(os.environ.get("AIRTEL_READ_TIMEOUT", "20"))

# Production safety guard: if DEBUG=False and live charges are on, keys must exist
if not DEBUG and PAYMENTS_ALLOW_LIVE_CHARGES:
    if not PAYCHANGU_PUBLIC_KEY or not PAYCHANGU_SECRET_KEY:
        import warnings
        warnings.warn(
            "PAYMENTS_ALLOW_LIVE_CHARGES=true but PayChangu keys are missing. "
            "Real charges will fail. Set PAYCHANGU_PUBLIC_KEY and PAYCHANGU_SECRET_KEY.",
            RuntimeWarning,
        )

# Device locking integration flags
MOCK_DEVICE_LOCKING = os.environ.get("MOCK_DEVICE_LOCKING", "true").lower() == "true"
ENABLE_KNOX = os.environ.get("ENABLE_KNOX", "false").lower() == "true"
ENABLE_NUOVOPAY = os.environ.get("ENABLE_NUOVOPAY", "false").lower() == "true"
ENABLE_UPYA = os.environ.get("ENABLE_UPYA", "false").lower() == "true"
ENABLE_PAYTRIGGER = os.environ.get("ENABLE_PAYTRIGGER", "false").lower() == "true"
ENABLE_PAYCHANGU = os.environ.get("ENABLE_PAYCHANGU", "false").lower() == "true"

# Knox MDM
KNOX_API_KEY = os.environ.get("KNOX_API_KEY", "")
KNOX_API_URL = os.environ.get("KNOX_API_URL", "https://api.samsungknox.com")

# NuovoPay MDM
NUOVOPAY_API_KEY = os.environ.get("NUOVOPAY_API_KEY", "")
NUOVOPAY_API_URL = os.environ.get("NUOVOPAY_API_URL", "https://api.nuovopay.com")

# Twilio SMS
SMS_ENABLED = os.getenv("SMS_ENABLED", "False").lower() == "true"
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER", "")
DEFAULT_SMS_LANGUAGE = os.getenv("DEFAULT_SMS_LANGUAGE", "ny")

# SendGrid Email
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "TengaSale Support <support@tengasale.africa>")
ADMIN_ALERT_EMAIL = os.environ.get("ADMIN_ALERT_EMAIL", "admin@tengasale.com")

# ── Device Telemetry (Connectivity Intelligence) ──────────────────────────────
# PayTrigger MDM telemetry
PAYTRIGGER_API_KEY = os.environ.get("PAYTRIGGER_API_KEY", "")
PAYTRIGGER_BASE_URL = os.environ.get("PAYTRIGGER_BASE_URL", "")

# Upya MDM telemetry
UPYA_API_KEY = os.environ.get("UPYA_API_KEY", "")
UPYA_BASE_URL = os.environ.get("UPYA_BASE_URL", "")

# File upload security
MAX_UPLOAD_SIZE_MB = int(os.environ.get("MAX_UPLOAD_SIZE_MB", "5"))
MAX_CALL_RECORDING_SIZE_MB = int(os.environ.get("MAX_CALL_RECORDING_SIZE_MB", "20"))
MAX_CALL_RECORDINGS_PER_APPLICATION = int(os.environ.get("MAX_CALL_RECORDINGS_PER_APPLICATION", "3"))
REQUIRE_CALL_RECORDING_FOR_APPROVAL = os.environ.get(
    "REQUIRE_CALL_RECORDING_FOR_APPROVAL", "false"
).lower() in ("true", "1", "yes", "on")
ALLOWED_KYC_MIME_TYPES = ["image/jpeg", "image/png", "image/webp", "application/pdf"]
ALLOWED_AUDIO_MIME_TYPES = [
    "audio/mpeg",
    "audio/mp3",
    "audio/wav",
    "audio/mp4",
    "audio/webm",
    "audio/ogg",
    "audio/x-wav",
]

# Customer correction token expiry (hours)
CORRECTION_TOKEN_EXPIRY_HOURS = int(os.environ.get("CORRECTION_TOKEN_EXPIRY_HOURS", "72"))

APP_VERSION = "1.0.0"

# ── TengaSale Legal / Company Details ─────────────────────────────────────────
TENGASALE_COMPANY_NAME = os.environ.get("TENGASALE_COMPANY_NAME", "Emajinet Limited t/a TengaSale")
TENGASALE_COMPANY_ADDRESS = os.environ.get("TENGASALE_COMPANY_ADDRESS", "Blantyre, Malawi")
TENGASALE_COMPANY_EMAIL = os.environ.get("TENGASALE_COMPANY_EMAIL", "info@tengasale.emajinet.africa")
TENGASALE_COMPANY_PHONE = os.environ.get("TENGASALE_COMPANY_PHONE", "+265 (0) XXX XXX XXX")
TENGASALE_GOVERNING_LAW = os.environ.get("TENGASALE_GOVERNING_LAW", "the laws of the Republic of Malawi")

# ── Deposit Access Period ─────────────────────────────────────────────────────
# Number of days of device access granted by the deposit payment.
# New contracts use this value. Existing contracts retain their stored deposit_access_days.
DEFAULT_DEPOSIT_ACCESS_DAYS = int(os.environ.get("DEFAULT_DEPOSIT_ACCESS_DAYS", "7"))

# ── Device Lock Integration Layer ─────────────────────────────────────────────
# Master switch — set True when a real provider is available.
# With False, all lock actions are no-ops but profiles/events are still created.
DEVICE_LOCK_ENABLED = os.environ.get("DEVICE_LOCK_ENABLED", "False").lower() in ("true", "1", "yes")

# Active lock provider: mock | samsung_knox | trustonic | paytrigger | none
DEVICE_LOCK_PROVIDER = os.environ.get("DEVICE_LOCK_PROVIDER", "mock")

# Strict mode: True = a lock failure blocks the related workflow step
DEVICE_LOCK_STRICT_MODE = os.environ.get("DEVICE_LOCK_STRICT_MODE", "False").lower() in ("true", "1", "yes")

# Automatic lifecycle hooks
DEVICE_LOCK_AUTO_ENROLL = os.environ.get("DEVICE_LOCK_AUTO_ENROLL", "False").lower() in ("true", "1", "yes")
DEVICE_LOCK_AUTO_LOCK = os.environ.get("DEVICE_LOCK_AUTO_LOCK", "False").lower() in ("true", "1", "yes")
DEVICE_LOCK_AUTO_UNLOCK = os.environ.get("DEVICE_LOCK_AUTO_UNLOCK", "False").lower() in ("true", "1", "yes")

# Provider API credentials (leave blank until real credentials are available)
DEVICE_LOCK_WEBHOOK_SECRET = os.environ.get("DEVICE_LOCK_WEBHOOK_SECRET", "")
DEVICE_LOCK_API_BASE_URL = os.environ.get("DEVICE_LOCK_API_BASE_URL", "")
DEVICE_LOCK_API_KEY = os.environ.get("DEVICE_LOCK_API_KEY", "")
DEVICE_LOCK_CLIENT_ID = os.environ.get("DEVICE_LOCK_CLIENT_ID", "")
DEVICE_LOCK_CLIENT_SECRET = os.environ.get("DEVICE_LOCK_CLIENT_SECRET", "")
DEVICE_LOCK_TIMEOUT_SECONDS = int(os.environ.get("DEVICE_LOCK_TIMEOUT_SECONDS", "20"))

# ── IMEI Verification Settings ────────────────────────────────────────────────
# Enable/disable the IMEI verification feature entirely
IMEI_CHECK_ENABLED = os.environ.get("IMEI_CHECK_ENABLED", "True") == "True"
# Strict mode: mismatch blocks submission; possible_match goes to underwriter review
IMEI_CHECK_STRICT_MODE = os.environ.get("IMEI_CHECK_STRICT_MODE", "True") == "True"
# Auto-verify IMEI when merchant submits the IMEI form
IMEI_CHECK_AUTO_VERIFY = os.environ.get("IMEI_CHECK_AUTO_VERIFY", "True") == "True"
# API credentials (development fallback only; override in production via environment)
IMEI_CHECK_USERNAME = os.environ.get("IMEI_CHECK_USERNAME", "PaulChris998")
IMEI_CHECK_API_KEY = os.environ.get("IMEI_CHECK_API_KEY", "nP7VE-ANKTC-YUzkZ-6e9Cc-4PKTh-DndJk")
IMEI_CHECK_ENDPOINT_BASE = os.environ.get("IMEI_CHECK_ENDPOINT_BASE", "https://dhru.checkimei.com")
IMEI_CHECK_ALPHA_ENDPOINT_BASE = os.environ.get("IMEI_CHECK_ALPHA_ENDPOINT_BASE", "https://alpha.imeicheck.com")
# Service ID for the IMEI check service (leave blank until confirmed)
IMEI_CHECK_SERVICE_ID = os.environ.get("IMEI_CHECK_SERVICE_ID", "")
# Request timeout in seconds
IMEI_CHECK_TIMEOUT_SECONDS = int(os.environ.get("IMEI_CHECK_TIMEOUT_SECONDS", "20"))

# ── Didit KYC (identity verification) ───────────────────────────────────────────
DIDIT_API_KEY = os.environ.get("DIDIT_API_KEY", "")
DIDIT_WORKFLOW_ID = os.environ.get("DIDIT_WORKFLOW_ID", "")
DIDIT_WEBHOOK_SECRET = os.environ.get("DIDIT_WEBHOOK_SECRET", "")
DIDIT_WEBHOOK_URL = os.environ.get("DIDIT_WEBHOOK_URL", "")
DIDIT_CALLBACK_URL = os.environ.get("DIDIT_CALLBACK_URL", "")
DIDIT_ALLOW_UNSIGNED_WEBHOOKS = os.environ.get("DIDIT_ALLOW_UNSIGNED_WEBHOOKS", "False").lower() in (
    "true",
    "1",
    "yes",
)
REQUIRE_DIDIT_KYC_BEFORE_APPROVAL = os.environ.get("REQUIRE_DIDIT_KYC_BEFORE_APPROVAL", "False").lower() in (
    "true",
    "1",
    "yes",
)
DIDIT_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("DIDIT_REQUEST_TIMEOUT_SECONDS", "15"))
DIDIT_SEND_EXPECTED_DETAILS = os.environ.get("DIDIT_SEND_EXPECTED_DETAILS", "False").lower() in (
    "true",
    "1",
    "yes",
)

# ── Merchant Administrator settings ──────────────────────────────────────────
# If True, Merchant Admins can only *recommend* approval; HQ must give final sign-off.
# Set to False to allow Merchant Admins to directly approve leads without HQ review.
REQUIRE_HQ_MERCHANT_APPROVAL = True

# ── Messaging / WhatsApp delivery settings ────────────────────────────────────
MESSAGING_ENABLED = os.environ.get("MESSAGING_ENABLED", "True").lower() in ("true", "1", "yes")
WHATSAPP_DELIVERY_ENABLED = os.environ.get("WHATSAPP_DELIVERY_ENABLED", "True").lower() in ("true", "1", "yes")
# Provider: mock | twilio_sandbox | twilio_production
WHATSAPP_PROVIDER = os.environ.get("WHATSAPP_PROVIDER", "mock").strip().lower()
if WHATSAPP_PROVIDER not in {"mock", "twilio_sandbox", "twilio_production"}:
    WHATSAPP_PROVIDER = "mock"
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_MESSAGING_SERVICE_SID = os.environ.get("TWILIO_MESSAGING_SERVICE_SID", "")
TWILIO_WHATSAPP_FROM = os.environ.get("TWILIO_WHATSAPP_FROM", os.environ.get("WHATSAPP_FROM_NUMBER", ""))
TWILIO_VALIDATE_SIGNATURE = os.environ.get("TWILIO_VALIDATE_SIGNATURE", "False").lower() in ("true", "1", "yes")
TWILIO_WEBHOOK_SECRET = os.environ.get("TWILIO_WEBHOOK_SECRET", "")
SITE_URL = os.environ.get("SITE_URL", "https://tengasale.onrender.com").strip().rstrip("/")
WHATSAPP_WEBHOOK_URL = os.environ.get("WHATSAPP_WEBHOOK_URL", "/tengasale/support/whatsapp/webhook/")
WHATSAPP_STATUS_CALLBACK_URL = os.environ.get("WHATSAPP_STATUS_CALLBACK_URL", "/tengasale/support/whatsapp/status/")
# Hours after contract completion to send the PDF
WHATSAPP_SEND_CONTRACT_AFTER_HOURS = int(os.environ.get("WHATSAPP_SEND_CONTRACT_AFTER_HOURS", "24"))
# Twilio WhatsApp credentials
WHATSAPP_API_KEY = os.environ.get("WHATSAPP_API_KEY", "")
WHATSAPP_API_SECRET = os.environ.get("WHATSAPP_API_SECRET", "")
# Meta / Facebook WhatsApp Business API
WHATSAPP_ACCESS_TOKEN = os.environ.get("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_FROM_NUMBER = os.environ.get("WHATSAPP_FROM_NUMBER", "")
WHATSAPP_TIMEOUT_SECONDS = int(os.environ.get("WHATSAPP_TIMEOUT_SECONDS", "20"))
# If True, generate publicly accessible PDF URLs for WhatsApp document sends.
# If False, use local file path (mock provider works; real providers may fail gracefully).
CONTRACT_PDF_PUBLIC_URL_MODE = os.environ.get("CONTRACT_PDF_PUBLIC_URL_MODE", "False").lower() in ("true", "1", "yes")
# Base URL used to build public PDF links (e.g. https://tengasale.onrender.com)
CONTRACT_PDF_BASE_URL = os.environ.get("CONTRACT_PDF_BASE_URL", "")

if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
