"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import sys

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file():
    """Load tengasale/.env for local development (does not override existing env vars)."""
    env_path = BASE_DIR / ".env"
    if not env_path.is_file():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_local_env_file()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-3mtl0z7s^6z9g$yac8tv*(^($um4o=592tmtrym6o&33**xjo^",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
    "tengasale.emajinet.africa",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://tengasale.emajinet.africa",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "accounts.apps.AccountsConfig",
    "merchants",
    "core",
    "geography",
    "applications",
    "deals",
    "earnings",
    "commissions",
    "rewards",
    "approvals",
    "contracts",
    "financing",
    "risk",
    "dashboard",
    "sales",
    "portal",
    "website",
    "merchant_admin.apps.MerchantAdminConfig",
    "support.apps.SupportConfig",
    "device_lock.apps.DeviceLockConfig",
    "notifications.apps.NotificationsConfig",
    "communications.apps.CommunicationsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.tengasale_support",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Blantyre"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# In development (DEBUG=True), serve source files directly — no collectstatic needed.
# In production, use whitenoise CompressedManifest for hashed, compressed assets.
if DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Cache — use LocMemCache by default (no external dependency needed)
# Upgrade to Redis/Memcached in production for multi-process deployments
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tengasale-default",
        "TIMEOUT": 3600,  # 1 hour default
    }
}

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

TENGASALE_WHATSAPP_NUMBER = os.environ.get("TENGASALE_WHATSAPP_NUMBER", "+265883596135")
TENGASALE_WHATSAPP_LINK = f"https://wa.me/{''.join(char for char in TENGASALE_WHATSAPP_NUMBER if char.isdigit())}"

TRUSTONIC_API_KEY = os.environ.get("TRUSTONIC_API_KEY", "")
TRUSTONIC_API_URL = os.environ.get("TRUSTONIC_API_URL", "")
UPYA_API_KEY = os.environ.get("UPYA_API_KEY", "")
UPYA_API_URL = os.environ.get("UPYA_API_URL", "")
PAYMENT_PROVIDER_API_KEY = os.environ.get("PAYMENT_PROVIDER_API_KEY", "")
PAYMENT_PROVIDER_API_URL = os.environ.get("PAYMENT_PROVIDER_API_URL", "")
SMS_PROVIDER_API_KEY = os.environ.get("SMS_PROVIDER_API_KEY", "")
SMS_PROVIDER_API_URL = os.environ.get("SMS_PROVIDER_API_URL", "")

# Payment providers
MOCK_PAYMENTS = os.environ.get("MOCK_PAYMENTS", "true").lower() == "true"
PAYCHANGU_PUBLIC_KEY = os.environ.get("PAYCHANGU_PUBLIC_KEY", "")
PAYCHANGU_SECRET_KEY = os.environ.get("PAYCHANGU_SECRET_KEY", "")
PAYCHANGU_WEBHOOK_SECRET = os.environ.get("PAYCHANGU_WEBHOOK_SECRET", "")
AIRTEL_MONEY_CLIENT_ID = os.environ.get("AIRTEL_MONEY_CLIENT_ID", "")
AIRTEL_MONEY_CLIENT_SECRET = os.environ.get("AIRTEL_MONEY_CLIENT_SECRET", "")
TNM_MPAMBA_API_KEY = os.environ.get("TNM_MPAMBA_API_KEY", "")
PAYTRIGGER_API_KEY = os.environ.get("PAYTRIGGER_API_KEY", "")

# Device locking integration flags
MOCK_DEVICE_LOCKING = os.environ.get("MOCK_DEVICE_LOCKING", "true").lower() == "true"
ENABLE_KNOX = os.environ.get("ENABLE_KNOX", "false").lower() == "true"
ENABLE_NUOVOPAY = os.environ.get("ENABLE_NUOVOPAY", "false").lower() == "true"
ENABLE_UPYA = os.environ.get("ENABLE_UPYA", "false").lower() == "true"
ENABLE_PAYTRIGGER = os.environ.get("ENABLE_PAYTRIGGER", "false").lower() == "true"
ENABLE_PAYCHANGU = os.environ.get("ENABLE_PAYCHANGU", "false").lower() == "true"

# Knox MDM
KNOX_API_KEY = os.environ.get("KNOX_API_KEY", "")
KNOX_API_URL = os.environ.get("KNOX_API_URL", "https://api.samsungknox.com")

# NuovoPay MDM
NUOVOPAY_API_KEY = os.environ.get("NUOVOPAY_API_KEY", "")
NUOVOPAY_API_URL = os.environ.get("NUOVOPAY_API_URL", "https://api.nuovopay.com")

# Twilio SMS
SMS_ENABLED = os.getenv("SMS_ENABLED", "False").lower() == "true"
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER", "")
DEFAULT_SMS_LANGUAGE = os.getenv("DEFAULT_SMS_LANGUAGE", "ny")

# SendGrid Email
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@tengasale.com")
ADMIN_ALERT_EMAIL = os.environ.get("ADMIN_ALERT_EMAIL", "admin@tengasale.com")

# File upload security
MAX_UPLOAD_SIZE_MB = int(os.environ.get("MAX_UPLOAD_SIZE_MB", "5"))
MAX_CALL_RECORDING_SIZE_MB = int(os.environ.get("MAX_CALL_RECORDING_SIZE_MB", "20"))
MAX_CALL_RECORDINGS_PER_APPLICATION = int(os.environ.get("MAX_CALL_RECORDINGS_PER_APPLICATION", "3"))
REQUIRE_CALL_RECORDING_FOR_APPROVAL = os.environ.get(
    "REQUIRE_CALL_RECORDING_FOR_APPROVAL", "true"
).lower() in ("true", "1", "yes", "on")
ALLOWED_KYC_MIME_TYPES = ["image/jpeg", "image/png", "image/webp", "application/pdf"]
ALLOWED_AUDIO_MIME_TYPES = [
    "audio/mpeg",
    "audio/mp3",
    "audio/wav",
    "audio/mp4",
    "audio/webm",
    "audio/ogg",
    "audio/x-wav",
]

# Customer correction token expiry (hours)
CORRECTION_TOKEN_EXPIRY_HOURS = int(os.environ.get("CORRECTION_TOKEN_EXPIRY_HOURS", "72"))

# PayChangu callback URL
PAYCHANGU_CALLBACK_URL = os.environ.get("PAYCHANGU_CALLBACK_URL", "")

APP_VERSION = "1.0.0"

# ── TengaSale Legal / Company Details ─────────────────────────────────────────
TENGASALE_COMPANY_NAME = os.environ.get("TENGASALE_COMPANY_NAME", "Emajinet Limited t/a TengaSale")
TENGASALE_COMPANY_ADDRESS = os.environ.get("TENGASALE_COMPANY_ADDRESS", "Blantyre, Malawi")
TENGASALE_COMPANY_EMAIL = os.environ.get("TENGASALE_COMPANY_EMAIL", "info@tengasale.emajinet.africa")
TENGASALE_COMPANY_PHONE = os.environ.get("TENGASALE_COMPANY_PHONE", "+265 (0) XXX XXX XXX")
TENGASALE_GOVERNING_LAW = os.environ.get("TENGASALE_GOVERNING_LAW", "the laws of the Republic of Malawi")

# ── Deposit Access Period ─────────────────────────────────────────────────────
# Number of days of device access granted by the deposit payment.
# New contracts use this value. Existing contracts retain their stored deposit_access_days.
DEFAULT_DEPOSIT_ACCESS_DAYS = int(os.environ.get("DEFAULT_DEPOSIT_ACCESS_DAYS", "7"))

# ── Device Lock Integration Layer ─────────────────────────────────────────────
# Master switch — set True when a real provider is available.
# With False, all lock actions are no-ops but profiles/events are still created.
DEVICE_LOCK_ENABLED = os.environ.get("DEVICE_LOCK_ENABLED", "False").lower() in ("true", "1", "yes")

# Active lock provider: mock | samsung_knox | trustonic | paytrigger | none
DEVICE_LOCK_PROVIDER = os.environ.get("DEVICE_LOCK_PROVIDER", "mock")

# Strict mode: True = a lock failure blocks the related workflow step
DEVICE_LOCK_STRICT_MODE = os.environ.get("DEVICE_LOCK_STRICT_MODE", "False").lower() in ("true", "1", "yes")

# Automatic lifecycle hooks
DEVICE_LOCK_AUTO_ENROLL = os.environ.get("DEVICE_LOCK_AUTO_ENROLL", "False").lower() in ("true", "1", "yes")
DEVICE_LOCK_AUTO_LOCK = os.environ.get("DEVICE_LOCK_AUTO_LOCK", "False").lower() in ("true", "1", "yes")
DEVICE_LOCK_AUTO_UNLOCK = os.environ.get("DEVICE_LOCK_AUTO_UNLOCK", "False").lower() in ("true", "1", "yes")

# Provider API credentials (leave blank until real credentials are available)
DEVICE_LOCK_WEBHOOK_SECRET = os.environ.get("DEVICE_LOCK_WEBHOOK_SECRET", "")
DEVICE_LOCK_API_BASE_URL = os.environ.get("DEVICE_LOCK_API_BASE_URL", "")
DEVICE_LOCK_API_KEY = os.environ.get("DEVICE_LOCK_API_KEY", "")
DEVICE_LOCK_CLIENT_ID = os.environ.get("DEVICE_LOCK_CLIENT_ID", "")
DEVICE_LOCK_CLIENT_SECRET = os.environ.get("DEVICE_LOCK_CLIENT_SECRET", "")
DEVICE_LOCK_TIMEOUT_SECONDS = int(os.environ.get("DEVICE_LOCK_TIMEOUT_SECONDS", "20"))

# ── IMEI Verification Settings ────────────────────────────────────────────────
# Enable/disable the IMEI verification feature entirely
IMEI_CHECK_ENABLED = os.environ.get("IMEI_CHECK_ENABLED", "True") == "True"
# Strict mode: mismatch blocks submission; possible_match goes to underwriter review
IMEI_CHECK_STRICT_MODE = os.environ.get("IMEI_CHECK_STRICT_MODE", "True") == "True"
# Auto-verify IMEI when merchant submits the IMEI form
IMEI_CHECK_AUTO_VERIFY = os.environ.get("IMEI_CHECK_AUTO_VERIFY", "True") == "True"
# API credentials (development fallback only; override in production via environment)
IMEI_CHECK_USERNAME = os.environ.get("IMEI_CHECK_USERNAME", "PaulChris998")
IMEI_CHECK_API_KEY = os.environ.get("IMEI_CHECK_API_KEY", "nP7VE-ANKTC-YUzkZ-6e9Cc-4PKTh-DndJk")
IMEI_CHECK_ENDPOINT_BASE = os.environ.get("IMEI_CHECK_ENDPOINT_BASE", "https://dhru.checkimei.com")
IMEI_CHECK_ALPHA_ENDPOINT_BASE = os.environ.get("IMEI_CHECK_ALPHA_ENDPOINT_BASE", "https://alpha.imeicheck.com")
# Service ID for the IMEI check service (leave blank until confirmed)
IMEI_CHECK_SERVICE_ID = os.environ.get("IMEI_CHECK_SERVICE_ID", "")
# Request timeout in seconds
IMEI_CHECK_TIMEOUT_SECONDS = int(os.environ.get("IMEI_CHECK_TIMEOUT_SECONDS", "20"))

# ── Didit KYC (identity verification) ───────────────────────────────────────────
DIDIT_API_KEY = os.environ.get("DIDIT_API_KEY", "")
DIDIT_WORKFLOW_ID = os.environ.get("DIDIT_WORKFLOW_ID", "")
DIDIT_WEBHOOK_SECRET = os.environ.get("DIDIT_WEBHOOK_SECRET", "")
DIDIT_WEBHOOK_URL = os.environ.get("DIDIT_WEBHOOK_URL", "")
DIDIT_CALLBACK_URL = os.environ.get("DIDIT_CALLBACK_URL", "")
DIDIT_ALLOW_UNSIGNED_WEBHOOKS = os.environ.get("DIDIT_ALLOW_UNSIGNED_WEBHOOKS", "False").lower() in (
    "true",
    "1",
    "yes",
)
REQUIRE_DIDIT_KYC_BEFORE_APPROVAL = os.environ.get("REQUIRE_DIDIT_KYC_BEFORE_APPROVAL", "False").lower() in (
    "true",
    "1",
    "yes",
)
DIDIT_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("DIDIT_REQUEST_TIMEOUT_SECONDS", "15"))
DIDIT_SEND_EXPECTED_DETAILS = os.environ.get("DIDIT_SEND_EXPECTED_DETAILS", "False").lower() in (
    "true",
    "1",
    "yes",
)

# ── Merchant Administrator settings ──────────────────────────────────────────
# If True, Merchant Admins can only *recommend* approval; HQ must give final sign-off.
# Set to False to allow Merchant Admins to directly approve leads without HQ review.
REQUIRE_HQ_MERCHANT_APPROVAL = True

# ── Messaging / WhatsApp delivery settings ────────────────────────────────────
MESSAGING_ENABLED = os.environ.get("MESSAGING_ENABLED", "True").lower() in ("true", "1", "yes")
WHATSAPP_DELIVERY_ENABLED = os.environ.get("WHATSAPP_DELIVERY_ENABLED", "True").lower() in ("true", "1", "yes")
# Provider: mock | twilio | meta_whatsapp
WHATSAPP_PROVIDER = os.environ.get("WHATSAPP_PROVIDER", "mock")
# Hours after contract completion to send the PDF
WHATSAPP_SEND_CONTRACT_AFTER_HOURS = int(os.environ.get("WHATSAPP_SEND_CONTRACT_AFTER_HOURS", "24"))
# Twilio WhatsApp credentials
WHATSAPP_API_KEY = os.environ.get("WHATSAPP_API_KEY", "")
WHATSAPP_API_SECRET = os.environ.get("WHATSAPP_API_SECRET", "")
# Meta / Facebook WhatsApp Business API
WHATSAPP_ACCESS_TOKEN = os.environ.get("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_FROM_NUMBER = os.environ.get("WHATSAPP_FROM_NUMBER", "")
WHATSAPP_TIMEOUT_SECONDS = int(os.environ.get("WHATSAPP_TIMEOUT_SECONDS", "20"))
# If True, generate publicly accessible PDF URLs for WhatsApp document sends.
# If False, use local file path (mock provider works; real providers may fail gracefully).
CONTRACT_PDF_PUBLIC_URL_MODE = os.environ.get("CONTRACT_PDF_PUBLIC_URL_MODE", "False").lower() in ("true", "1", "yes")
# Base URL used to build public PDF links (e.g. https://tengasale.onrender.com)
CONTRACT_PDF_BASE_URL = os.environ.get("CONTRACT_PDF_BASE_URL", "")

if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
