# Generated by Django 6.0.5 on 2026-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0003_reviewquestion_reviewanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="underwriterreview",
            name="identity_images_clear",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="identity_selfie_matches",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
