# Generated by Django 6.0.5 on 2026-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0004_add_identity_selfie_images_clear_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="underwriterreview",
            name="contacts_reachable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="deal_deposit_understood",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="deal_legal_understood",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="deal_lock_understood",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="deal_phone_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="deal_repayment_understood",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="guarantor_confident_repayment",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="guarantor_confirmed_customer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="guarantor_spoken",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="underwriterreview",
            name="location_address_clear",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
