# Generated by Django 6.0.5 on 2026-06-06 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_didit_manual_override_audit'),
        ('approvals', '0005_add_guarantor_location_deal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCallQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_consent_acknowledged', models.BooleanField(default=False)),
                ('identity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('work_context_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('income_confidence_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_understanding_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_understanding_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('determined_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('review', 'Needs Review'), ('reject', 'Recommend Reject')], default='review', max_length=32)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_questionnaire', to='applications.financingapplication')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_call_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Call Questionnaire',
                'verbose_name_plural': 'Customer Call Questionnaires',
                'ordering': ['-completed_at', '-updated_at'],
            },
        ),
    ]
