# Generated by Django 6.0.5 on 2026-06-07 11:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_didit_manual_override_audit'),
        ('approvals', '0006_customercallquestionnaire'),
        ('commissions', '0002_merchantcontractpayout_commissionledger_and_more'),
        ('portal', '0014_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCOffenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('default_penalty_mwk', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QC Offense Type',
                'verbose_name_plural': 'QC Offense Types',
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UnderwriterCallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='underwriter_call_recordings/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('consent_acknowledged', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_qc', 'Pending QC'), ('passed_qc', 'Passed QC'), ('failed_qc', 'Failed QC')], default='pending_qc', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('qc_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underwriter_call_recordings', to='applications.financingapplication')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underwriter_call_recordings', to='portal.paymentcontract')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_underwriter_call_recordings', to=settings.AUTH_USER_MODEL)),
                ('underwriter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underwriter_call_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Underwriter Call Recording',
                'verbose_name_plural': 'Underwriter Call Recordings',
                'ordering': ['-uploaded_at'],
                'permissions': [('underwriter_upload_call_recording', 'Can upload underwriter call recordings'), ('hq_review_call_recording_qc', 'Can review underwriter call recording QC')],
            },
        ),
        migrations.CreateModel(
            name='UnderwriterQCPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_mwk', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('reversed', 'Reversed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('payroll_period', models.DateField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underwriter_qc_penalties', to='applications.financingapplication')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underwriter_qc_penalties', to='portal.paymentcontract')),
                ('evidence_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_penalties', to='approvals.underwritercallrecording')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_qc_penalties', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_penalties', to='commissions.commissionledger')),
                ('offense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='approvals.qcoffensetype')),
                ('reversal_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_qc_penalties', to='commissions.commissionledger')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_qc_penalties', to=settings.AUTH_USER_MODEL)),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Underwriter QC Penalty',
                'verbose_name_plural': 'Underwriter QC Penalties',
                'ordering': ['-issued_at'],
                'permissions': [('hq_issue_qc_penalty', 'Can issue underwriter QC penalties'), ('hq_reverse_qc_penalty', 'Can reverse underwriter QC penalties'), ('hq_override_penalty_amount', 'Can override underwriter QC penalty amount'), ('underwriter_view_own_penalties', 'Can view own underwriter QC penalties'), ('underwriter_dispute_penalty', 'Can dispute own underwriter QC penalties')],
            },
        ),
    ]
