# Generated by Django 6.0.5 on 2026-06-08 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('underwriter', 'Underwriter'), ('staff', 'Staff / Employee'), ('hq', 'HQ / Admin'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('maps_to_category', models.CharField(choices=[('payment', 'Payment issue'), ('access', 'Login / access issue'), ('merchant_onboarding', 'Merchant onboarding issue'), ('underwriter', 'Underwriter issue'), ('device_lock', 'Device lock issue'), ('app_error', 'Application error'), ('contract', 'Contract issue'), ('payout', 'Payout issue'), ('data_correction', 'Data correction request'), ('other', 'Other')], default='other', max_length=30)),
                ('chatbot_menu_label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Support Category',
                'verbose_name_plural': 'Support Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('whatsapp_name', models.CharField(blank=True, max_length=120)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('underwriter', 'Underwriter'), ('staff', 'Staff / Employee'), ('hq', 'HQ / Admin'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('current_state', models.CharField(choices=[('welcome', 'Welcome / Main Menu'), ('customer', 'Customer Menu'), ('merchant', 'Merchant Menu'), ('underwriter', 'Underwriter Menu'), ('staff', 'Staff Menu'), ('fraud', 'Fraud Report Menu'), ('issue', 'Issue Captured'), ('ticket_done', 'Ticket Created'), ('human', 'Awaiting Human Agent')], default='welcome', max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('ny', 'Chichewa')], default='en', max_length=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='support.supportticket')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Conversation',
                'verbose_name_plural': 'Support Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('admin', 'Admin'), ('system', 'System')], max_length=10)),
                ('message', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportconversation')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
