# Generated by Django 6.0.5 on 2026-06-13 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_ticket_numbers(apps, schema_editor):
    SupportTicket = apps.get_model('support', 'SupportTicket')
    for ticket in SupportTicket.objects.filter(ticket_number__isnull=True).order_by('pk'):
        created_at = ticket.created_at or timezone.now()
        ticket.ticket_number = f"TS-{created_at.year}-{ticket.pk:06d}"
        ticket.save(update_fields=['ticket_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_certificate_file_and_more'),
        ('support', '0002_supportcategory_supportconversation_supportmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='escalation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_message_preview',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='linked_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='linked_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='linked_underwriter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underwriter_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sender_phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sender_type',
            field=models.CharField(blank=True, default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True),
        ),
        migrations.RunPython(backfill_ticket_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='supportcategory',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='supportcategory',
            name='maps_to_category',
            field=models.CharField(choices=[('payment', 'Payment issue'), ('access', 'Login / access issue'), ('merchant_onboarding', 'Merchant onboarding issue'), ('underwriter', 'Underwriter issue'), ('device_lock', 'Device lock issue'), ('app_error', 'Application error'), ('contract', 'Contract issue'), ('payout', 'Payout issue'), ('data_correction', 'Data correction request'), ('application_status', 'Application status'), ('payment_not_reflecting', 'Payment not reflecting'), ('unlock_request', 'Unlock request'), ('deposit_issue', 'Deposit issue'), ('wrong_phone_number', 'Wrong phone number'), ('wrong_id_details', 'Wrong ID details'), ('contract_issue', 'Contract issue'), ('warranty_issue', 'Warranty / damaged phone'), ('guarantor_issue', 'Guarantor issue'), ('merchant_complaint', 'Merchant complaint'), ('underwriter_complaint', 'Underwriter complaint'), ('general_support', 'General support'), ('merchant_support', 'Merchant support'), ('handover_problem', 'Handover problem'), ('imei_submission_problem', 'IMEI submission problem'), ('deposit_confirmation_issue', 'Deposit confirmation issue'), ('stock_issue', 'Stock issue'), ('contract_generation_issue', 'Contract generation issue'), ('merchant_commission_issue', 'Merchant commission issue'), ('suspected_customer_fraud', 'Suspected customer fraud'), ('finance_review', 'Finance review'), ('recovery_review', 'Recovery review'), ('legal_review', 'Legal review'), ('management_escalation', 'Management escalation'), ('fraud_report', 'Fraud report'), ('system_issue', 'System issue'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('payment', 'Payment issue'), ('access', 'Login / access issue'), ('merchant_onboarding', 'Merchant onboarding issue'), ('underwriter', 'Underwriter issue'), ('device_lock', 'Device lock issue'), ('app_error', 'Application error'), ('contract', 'Contract issue'), ('payout', 'Payout issue'), ('data_correction', 'Data correction request'), ('application_status', 'Application status'), ('payment_not_reflecting', 'Payment not reflecting'), ('unlock_request', 'Unlock request'), ('deposit_issue', 'Deposit issue'), ('wrong_phone_number', 'Wrong phone number'), ('wrong_id_details', 'Wrong ID details'), ('contract_issue', 'Contract issue'), ('warranty_issue', 'Warranty / damaged phone'), ('guarantor_issue', 'Guarantor issue'), ('merchant_complaint', 'Merchant complaint'), ('underwriter_complaint', 'Underwriter complaint'), ('general_support', 'General support'), ('merchant_support', 'Merchant support'), ('handover_problem', 'Handover problem'), ('imei_submission_problem', 'IMEI submission problem'), ('deposit_confirmation_issue', 'Deposit confirmation issue'), ('stock_issue', 'Stock issue'), ('contract_generation_issue', 'Contract generation issue'), ('merchant_commission_issue', 'Merchant commission issue'), ('suspected_customer_fraud', 'Suspected customer fraud'), ('finance_review', 'Finance review'), ('recovery_review', 'Recovery review'), ('legal_review', 'Legal review'), ('management_escalation', 'Management escalation'), ('fraud_report', 'Fraud report'), ('system_issue', 'System issue'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting on User'), ('waiting_for_customer', 'Waiting for Customer'), ('waiting_provider', 'Waiting on Provider'), ('escalated', 'Escalated to HQ'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportTicketAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(blank=True, default='', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='support.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketInternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_note_entries', to='support.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(db_index=True, max_length=30, unique=True)),
                ('whatsapp_id', models.CharField(blank=True, default='', max_length=80)),
                ('profile_name', models.CharField(blank=True, default='', max_length=160)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('underwriter', 'Underwriter'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('linked_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_customer_contacts', to=settings.AUTH_USER_MODEL)),
                ('linked_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to='merchants.merchant')),
                ('linked_underwriter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_underwriter_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='linked_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.whatsappcontact'),
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_for_customer', 'Waiting for Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=30)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='support.supportticket')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='support.whatsappcontact')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('twilio', 'Twilio')], default='mock', max_length=20)),
                ('provider_message_sid', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('provider_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('undelivered', 'Undelivered'), ('received', 'Received'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('from_phone', models.CharField(blank=True, default='', max_length=30)),
                ('to_phone', models.CharField(blank=True, default='', max_length=30)),
                ('body', models.TextField(blank=True, default='')),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('media_json', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.whatsappconversation')),
                ('sent_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='support.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
