# Generated by Django 6.0.5 on 2026-06-11 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('portal', '0014_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference', models.CharField(db_index=True, max_length=60, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('airtel_money_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('airtel_transaction_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('airtel_reference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('customer_msisdn', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MWK', max_length=5)),
                ('purpose', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('INSTALLMENT', 'Installment'), ('ARREARS', 'Arrears'), ('UNLOCK', 'Unlock'), ('REFUND', 'Refund'), ('COMMISSION', 'Commission'), ('TEST', 'Test')], max_length=20)),
                ('direction', models.CharField(choices=[('COLLECTION', 'Collection'), ('DISBURSEMENT', 'Disbursement')], default='COLLECTION', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired'), ('UNKNOWN', 'Unknown')], default='INITIATED', max_length=20)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('callback_verified', models.BooleanField(default=False)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_success_at', models.DateTimeField(blank=True, null=True)),
                ('processing_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airtel_transactions', to='portal.paymentcontract')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airtel_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airtel_transaction', to='portal.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirtelCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_headers', models.JSONField(blank=True, default=dict)),
                ('raw_body', models.TextField()),
                ('parsed_body', models.JSONField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('duplicate', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='payments.airteltransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='airteltransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_ai_status_e28e56_idx'),
        ),
        migrations.AddIndex(
            model_name='airteltransaction',
            index=models.Index(fields=['purpose', 'direction'], name='payments_ai_purpose_6c305b_idx'),
        ),
    ]
