# Generated by Django 6.0.5 on 2026-07-14 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_ussdpaymentintent_ussdsessionlog'),
        ('portal', '0014_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airteltransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='airteltransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('airtel_money_id__isnull', False), models.Q(('airtel_money_id', ''), _negated=True)), fields=('airtel_money_id',), name='uniq_airtel_money_id_when_present'),
        ),
        migrations.AddConstraint(
            model_name='airteltransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('airtel_transaction_id__isnull', False), models.Q(('airtel_transaction_id', ''), _negated=True)), fields=('airtel_transaction_id',), name='uniq_airtel_tx_id_when_present'),
        ),
    ]
