# Generated by Django 6.0.5 on 2026-07-14 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_airteltransaction_completed_at_and_more'),
        ('portal', '0014_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airteltransaction',
            name='duplicate_callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='environment',
            field=models.CharField(db_index=True, default='staging', max_length=20),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='provider',
            field=models.CharField(db_index=True, default='airtel_money', max_length=30),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='repayment_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airteltransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('DRY_RUN', 'Dry run'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired'), ('UNKNOWN', 'Unknown')], default='INITIATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='airteltransaction',
            index=models.Index(fields=['environment', 'status'], name='payments_ai_environ_8c8aa6_idx'),
        ),
    ]
