# Generated by Django 6.0.5 on 2026-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_airteltransaction_partial_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='authentication_mode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='body_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='error_class',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='extracted_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='matched_field',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='matched_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='matching_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='processing_state',
            field=models.CharField(db_index=True, default='RECEIVED', max_length=40),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='request_method',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='request_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='response_body',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='response_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='signature_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='enquiry_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='initiation_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='last_enquiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='last_enquiry_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='last_enquiry_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='last_enquiry_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='last_enquiry_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='last_enquiry_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='provider_id_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='provider_identifier_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='reconciliation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='reconciliation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airteltransaction',
            name='internal_reference',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
