# Generated by Django 6.0.5 on 2026-07-21 10:50

import payments.models
import secrets
from django.db import migrations, models


def populate_status_tokens(apps, schema_editor):
    AirtelTransaction = apps.get_model('payments', 'AirtelTransaction')
    for row in AirtelTransaction.objects.filter(status_token__isnull=True).iterator():
        row.status_token = secrets.token_urlsafe(24)
        row.save(update_fields=['status_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_airtelcallbacklog_authentication_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='body_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='candidate_identifiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='forwarded_for',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='processing_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='provider_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='query_string',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='real_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='status_token',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(populate_status_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='airteltransaction',
            name='status_token',
            field=models.CharField(default=payments.models.generate_status_token, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='airtelcallbacklog',
            index=models.Index(fields=['created_at'], name='payments_ai_created_241209_idx'),
        ),
        migrations.AddIndex(
            model_name='airtelcallbacklog',
            index=models.Index(fields=['response_status', 'created_at'], name='payments_ai_respons_66a635_idx'),
        ),
        migrations.AddIndex(
            model_name='airtelcallbacklog',
            index=models.Index(fields=['processing_state', 'created_at'], name='payments_ai_process_6d40d0_idx'),
        ),
    ]
