# Generated by Django 6.0.5 on 2026-07-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_airtelcallbacklog_body_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='candidate_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='initiation_http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='initiation_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='last_enquiry_http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AirtelEnquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_status', models.CharField(blank=True, max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_logs', to='payments.airteltransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
