# Generated by Django 6.0.5 on 2026-07-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_airtelcallbacklog_candidate_suggestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='extracted_provider_identifiers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='extracted_subscriber',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='replay_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replays', to='payments.airtelcallbacklog'),
        ),
        migrations.CreateModel(
            name='AirtelCallbackProcessingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('initiated_by', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(default='RECEIVED', max_length=40)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_attempts', to='payments.airtelcallbacklog')),
            ],
            options={
                'ordering': ['started_at'],
                'constraints': [models.UniqueConstraint(fields=('callback', 'attempt_number'), name='uniq_airtel_callback_attempt')],
            },
        ),
    ]
