# Generated by Django 6.0.5 on 2026-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_airtelcallbacklog_signature_validation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtelcallbacklog',
            name='extracted_airtel_money_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
