# Generated by Django 6.0.5 on 2026-07-25 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_airtelcallbacklog_extracted_airtel_money_id'),
        ('portal', '0017_airtel_retry_supersession_and_expired_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airteltransaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='potential_overpayment',
            field=models.BooleanField(default=False, help_text='A confirmed success arrived after another attempt in the same retry chain already posted. Requires operator review.'),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='retry_of',
            field=models.ForeignKey(blank=True, help_text='The prior attempt (for the same customer payment action) that this transaction replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='payments.airteltransaction'),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airteltransaction',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='The newer attempt that replaced this one after it went stale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='payments.airteltransaction'),
        ),
        migrations.AddIndex(
            model_name='airteltransaction',
            index=models.Index(fields=['reconciliation_required', 'created_at'], name='payments_ai_reconci_a4dba0_idx'),
        ),
    ]
