# Generated by Django 6.0.5 on 2026-08-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_airtel_retry_supersession_and_expired_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('normalized_mobile', models.CharField(db_index=True, max_length=15)),
                ('service_code', models.CharField(blank=True, max_length=64)),
                ('provider', models.CharField(default='generic', max_length=40)),
                ('state', models.CharField(default='ROOT', max_length=40)),
                ('selected_contract_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('selected_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
