# Generated by Django 6.0.5 on 2026-05-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_add_demographic_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="confidence_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="recommendation_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Human-readable rule-based recommendation note.",
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="repayment_confidence_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Rule-based repayment confidence estimate 0–100. Null means not yet calculated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="risk_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low risk"),
                    ("medium", "Medium risk"),
                    ("high", "High risk"),
                ],
                default="",
                help_text="Risk band derived from confidence score.",
                max_length=10,
            ),
        ),
    ]
