# Generated by Django 6.0.5 on 2026-05-31 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_repayment_confidence_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="imei_api_brand",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_api_model",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_match_confidence",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_order_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_override_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imei_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_override_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_raw_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_verification_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_verification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("matched", "Matched"),
                    ("possible_match", "Possible match"),
                    ("mismatch", "Mismatch"),
                    ("unknown", "Unknown"),
                    ("api_error", "API error"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="imei_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
