# Generated by Django 6.0.5 on 2026-05-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_imei_verification_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financingapplication",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", "Select gender"), ("male", "Male"), ("female", "Female")],
                default="",
                max_length=10,
            ),
        ),
    ]
