# Generated by Django 6.0.5 on 2026-06-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_financingapplication_term_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingapplication',
            name='phone_verification_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('verified', 'Verified'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_sent', max_length=30),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
