# Generated by Django 6.0.5 on 2026-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_financingapplication_phone_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingapplication',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='imei_number_2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='locking_confirmation_status',
            field=models.CharField(choices=[('not_confirmed', 'Not confirmed'), ('confirmed', 'Confirmed'), ('pending', 'Pending sync')], default='not_confirmed', max_length=30),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='locking_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='financingapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('started', 'Start'), ('customer_details', 'Customer Details'), ('device_selection', 'Device Selection'), ('kyc', 'KYC'), ('kyc_capture', 'KYC Capture'), ('location', 'Location'), ('location_details', 'Location Details'), ('work', 'Work'), ('work_details', 'Work Details'), ('signature', 'Signature'), ('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('under_review', 'Under Review'), ('correction_requested', 'Correction Requested'), ('sent_back', 'Sent Back'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('approved_pending_device_lock', 'Approved - Pending Device Lock'), ('device_locked', 'Device Locked'), ('active_contract', 'Active Contract'), ('rejected', 'Rejected'), ('contract_terms', 'Contract Terms'), ('contract_signature', 'Contract Signature'), ('imei_entry', 'IMEI Entry'), ('contract_creating', 'Contract Creating'), ('warranty_check', 'Warranty Check'), ('locking', 'Locking'), ('deposit_pending', 'Deposit Pending'), ('contract_complete', 'Contract Complete'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('imei_required', 'IMEI Required')], default='started', max_length=40),
        ),
    ]
