# Generated by Django 6.0.5 on 2026-06-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_didit_manual_override_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingapplication',
            name='first_smartphone',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
