# Generated by Django 6.0.5 on 2026-06-01 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_alter_financingapplication_gender"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="completed_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="contract_pdfs/completed/"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="initial_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="contract_pdfs/initial/"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="ownership_transfer_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_accepted_ip",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_otp_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_otp_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ContractDocumentDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "normalized_customer_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("manual", "Manual"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_at_snapshot",
                    models.DateTimeField(
                        blank=True,
                        help_text="Snapshot of contract.completed_at at time of scheduling.",
                        null=True,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="contract_pdfs/delivery/"
                    ),
                ),
                ("pdf_url", models.CharField(blank=True, max_length=500)),
                ("message_text", models.TextField(blank=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "Mock (Test)"),
                            ("twilio", "Twilio WhatsApp"),
                            ("meta_whatsapp", "Meta WhatsApp Business"),
                            ("other", "Other"),
                        ],
                        default="mock",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                ("provider_response", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_deliveries",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_deliveries",
                        to="contracts.contract",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Document Delivery",
                "verbose_name_plural": "Contract Document Deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["delivery_status", "scheduled_for"],
                        name="contracts_c_deliver_0b68b3_idx",
                    ),
                    models.Index(
                        fields=["contract", "channel"],
                        name="contracts_c_contrac_2a44e7_idx",
                    ),
                ],
            },
        ),
    ]
