# Generated by Django 6.0.5 on 2026-06-01 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_alter_financingapplication_gender"),
        ("contracts", "0002_contract_completed_at_contract_completed_pdf_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="completed_bundle_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="contract_pdfs/bundle_completed/"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_bundle_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="contract_pdfs/bundle/"
            ),
        ),
        migrations.CreateModel(
            name="LegalDocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("customer_contract_summary", "Customer Contract Summary"),
                            ("master_terms", "Master Terms and Conditions"),
                            ("privacy_notice", "Privacy Notice"),
                            ("device_lock_terms", "Device Lock Terms"),
                        ],
                        max_length=40,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "body_html",
                    models.TextField(
                        help_text="Full HTML content of this legal document version."
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True, null=True, upload_to="legal_docs/source/"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of body_html for integrity verification.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Document Template",
                "verbose_name_plural": "Legal Document Templates",
                "ordering": ["-effective_from", "-version"],
                "unique_together": {("document_type", "version")},
            },
        ),
        migrations.CreateModel(
            name="LegalAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_name", models.CharField(blank=True, max_length=150)),
                ("accepted_phone", models.CharField(blank=True, max_length=20)),
                ("accepted_national_id", models.CharField(blank=True, max_length=20)),
                (
                    "acceptance_method",
                    models.CharField(
                        choices=[
                            ("otp", "OTP Verification"),
                            ("digital_signature", "Digital/Touchscreen Signature"),
                            ("mobile_acceptance", "Mobile Acceptance (Checkbox/Tap)"),
                            ("biometric_confirmation", "Biometric Confirmation"),
                            ("staff_confirmed", "Staff Confirmed"),
                        ],
                        default="mobile_acceptance",
                        max_length=30,
                    ),
                ),
                ("accepted_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_reference", models.CharField(blank=True, max_length=200)),
                ("otp_reference", models.CharField(blank=True, max_length=50)),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="legal_signatures/"
                    ),
                ),
                (
                    "acceptance_text_snapshot",
                    models.TextField(
                        blank=True,
                        help_text="Snapshot of document title/version at time of acceptance for audit purposes.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_acceptances",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_acceptances",
                        to="contracts.contract",
                    ),
                ),
                (
                    "legal_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="contracts.legaldocumenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Acceptance",
                "verbose_name_plural": "Legal Acceptances",
                "ordering": ["-accepted_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "legal_document"],
                        name="contracts_l_applica_181855_idx",
                    ),
                    models.Index(
                        fields=["contract", "legal_document"],
                        name="contracts_l_contrac_2b96fe_idx",
                    ),
                ],
            },
        ),
    ]
