# Generated by Django 6.0.5 on 2026-06-01 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_active_at_contract_completed_bundle_pdf_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="term_months",
            field=models.PositiveIntegerField(
                default=12, help_text="Contract term in months: 3, 6, or 12"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms_confirmed_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="terms_version",
            field=models.CharField(blank=True, default="v1", max_length=20),
        ),
    ]
