# Generated by Django 6.0.5 on 2026-06-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_term_months_contract_terms_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='deposit_payer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='deposit_payment_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='deposit_payment_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('checkout_created', 'Checkout Created'), ('awaiting_confirmation', 'Awaiting Customer Confirmation'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('amount_mismatch', 'Amount Mismatch — Needs Review')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='deposit_payment_tx_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
